/*this file generated by GL_java_2_c.java ,dont modify it manual.*/
#include <stdio.h>
#include <string.h>

#include <glad.h>

#include "metadata.h"

#include "jvm.h"
#include "media.h"

void func_org_mini_gl_GL_glActiveTexture__I_V(JThreadRuntime *runtime, s32 ptexture) {
    

    glActiveTexture((GLenum)ptexture);
    
    
}
void func_org_mini_gl_GL_glAttachShader__II_V(JThreadRuntime *runtime, s32 pprogram, s32 pshader) {
    

    glAttachShader((GLuint)pprogram, (GLuint)pshader);
    
    
}
void func_org_mini_gl_GL_glBindAttribLocation__II_3B_V(JThreadRuntime *runtime, s32 pprogram, s32 pindex, JArray *pname) {
    
    s32 offset_pname = 0;    __refer ptr_pname = (__refer)(intptr_t) offset_pname;
    if(pname) {
        s32 bytes_pname = data_type_bytes[pname->prop.arr_type] * offset_pname;
        ptr_pname = &pname->prop.as_s8_arr[bytes_pname];
    }

    glBindAttribLocation((GLuint)pprogram, (GLuint)pindex, (const GLchar*)(ptr_pname));
    
    
}
void func_org_mini_gl_GL_glBindBuffer__II_V(JThreadRuntime *runtime, s32 ptarget, s32 pbuffer) {
    

    glBindBuffer((GLenum)ptarget, (GLuint)pbuffer);
    
    
}
void func_org_mini_gl_GL_glBindFramebuffer__II_V(JThreadRuntime *runtime, s32 ptarget, s32 pframebuffer) {
    

    glBindFramebuffer((GLenum)ptarget, (GLuint)pframebuffer);
    
    
}
void func_org_mini_gl_GL_glBindRenderbuffer__II_V(JThreadRuntime *runtime, s32 ptarget, s32 prenderbuffer) {
    

    glBindRenderbuffer((GLenum)ptarget, (GLuint)prenderbuffer);
    
    
}
void func_org_mini_gl_GL_glBindTexture__II_V(JThreadRuntime *runtime, s32 ptarget, s32 ptexture) {
    

    glBindTexture((GLenum)ptarget, (GLuint)ptexture);
    
    
}
void func_org_mini_gl_GL_glBlendColor__FFFF_V(JThreadRuntime *runtime, f32 pred, f32 pgreen, f32 pblue, f32 palpha) {
    

    glBlendColor((GLfloat)pred, (GLfloat)pgreen, (GLfloat)pblue, (GLfloat)palpha);
    
    
}
void func_org_mini_gl_GL_glBlendEquation__I_V(JThreadRuntime *runtime, s32 pmode) {
    

    glBlendEquation((GLenum)pmode);
    
    
}
void func_org_mini_gl_GL_glBlendEquationSeparate__II_V(JThreadRuntime *runtime, s32 pmodeRGB, s32 pmodeAlpha) {
    

    glBlendEquationSeparate((GLenum)pmodeRGB, (GLenum)pmodeAlpha);
    
    
}
void func_org_mini_gl_GL_glBlendFunc__II_V(JThreadRuntime *runtime, s32 psfactor, s32 pdfactor) {
    

    glBlendFunc((GLenum)psfactor, (GLenum)pdfactor);
    
    
}
void func_org_mini_gl_GL_glBlendFuncSeparate__IIII_V(JThreadRuntime *runtime, s32 psfactorRGB, s32 pdfactorRGB, s32 psfactorAlpha, s32 pdfactorAlpha) {
    

    glBlendFuncSeparate((GLenum)psfactorRGB, (GLenum)pdfactorRGB, (GLenum)psfactorAlpha, (GLenum)pdfactorAlpha);
    
    
}
void func_org_mini_gl_GL_glBufferData__IJLjava_lang_Object_2II_V(JThreadRuntime *runtime, s32 ptarget, s64 psize, struct java_lang_Object *pdata, s32 offset_pdata, s32 pusage) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glBufferData((GLenum)ptarget, (GLsizeiptr)psize, (const void*)(ptr_pdata), (GLenum)pusage);
    
    
}
void func_org_mini_gl_GL_glBufferSubData__IJJLjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 ptarget, s64 poffset, s64 psize, struct java_lang_Object *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glBufferSubData((GLenum)ptarget, (GLintptr)poffset, (GLsizeiptr)psize, (const void*)(ptr_pdata));
    
    
}
s32 func_org_mini_gl_GL_glCheckFramebufferStatus__I_I(JThreadRuntime *runtime, s32 ptarget) {
    

    GLenum _re_val = glCheckFramebufferStatus((GLenum)ptarget);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glClear__I_V(JThreadRuntime *runtime, s32 pmask) {
    

    glClear((GLbitfield)pmask);
    
    
}
void func_org_mini_gl_GL_glClearColor__FFFF_V(JThreadRuntime *runtime, f32 pred, f32 pgreen, f32 pblue, f32 palpha) {
    

    glClearColor((GLfloat)pred, (GLfloat)pgreen, (GLfloat)pblue, (GLfloat)palpha);
    
    
}
void func_org_mini_gl_GL_glClearDepthf__F_V(JThreadRuntime *runtime, f32 pd) {
    

    glClearDepthf((GLfloat)pd);
    
    
}
void func_org_mini_gl_GL_glClearStencil__I_V(JThreadRuntime *runtime, s32 ps) {
    

    glClearStencil((GLint)ps);
    
    
}
void func_org_mini_gl_GL_glColorMask__IIII_V(JThreadRuntime *runtime, s32 pred, s32 pgreen, s32 pblue, s32 palpha) {
    

    glColorMask((GLboolean)pred, (GLboolean)pgreen, (GLboolean)pblue, (GLboolean)palpha);
    
    
}
void func_org_mini_gl_GL_glCompileShader__I_V(JThreadRuntime *runtime, s32 pshader) {
    

    glCompileShader((GLuint)pshader);
    
    
}
void func_org_mini_gl_GL_glCompressedTexImage2D__IIIIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pinternalformat, s32 pwidth, s32 pheight, s32 pborder, s32 pimageSize, struct java_lang_Object *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glCompressedTexImage2D((GLenum)ptarget, (GLint)plevel, (GLenum)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight, (GLint)pborder, (GLsizei)pimageSize, (const void*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glCompressedTexSubImage2D__IIIIIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pxoffset, s32 pyoffset, s32 pwidth, s32 pheight, s32 pformat, s32 pimageSize, struct java_lang_Object *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glCompressedTexSubImage2D((GLenum)ptarget, (GLint)plevel, (GLint)pxoffset, (GLint)pyoffset, (GLsizei)pwidth, (GLsizei)pheight, (GLenum)pformat, (GLsizei)pimageSize, (const void*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glCopyTexImage2D__IIIIIIII_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pinternalformat, s32 px, s32 py, s32 pwidth, s32 pheight, s32 pborder) {
    

    glCopyTexImage2D((GLenum)ptarget, (GLint)plevel, (GLenum)pinternalformat, (GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight, (GLint)pborder);
    
    
}
void func_org_mini_gl_GL_glCopyTexSubImage2D__IIIIIIII_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pxoffset, s32 pyoffset, s32 px, s32 py, s32 pwidth, s32 pheight) {
    

    glCopyTexSubImage2D((GLenum)ptarget, (GLint)plevel, (GLint)pxoffset, (GLint)pyoffset, (GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight);
    
    
}
s32 func_org_mini_gl_GL_glCreateProgram___I(JThreadRuntime *runtime) {
    

    GLuint _re_val = glCreateProgram();
    return *((s32*)&_re_val);
    
}
s32 func_org_mini_gl_GL_glCreateShader__I_I(JThreadRuntime *runtime, s32 ptype) {
    

    GLuint _re_val = glCreateShader((GLenum)ptype);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glCullFace__I_V(JThreadRuntime *runtime, s32 pmode) {
    

    glCullFace((GLenum)pmode);
    
    
}
void func_org_mini_gl_GL_glDeleteBuffers__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *pbuffers, s32 offset_pbuffers) {
    
    __refer ptr_pbuffers = (__refer)(intptr_t) offset_pbuffers;
    if(pbuffers) {
        s32 bytes_pbuffers = data_type_bytes[pbuffers->prop.arr_type] * offset_pbuffers;
        ptr_pbuffers = &pbuffers->prop.as_s8_arr[bytes_pbuffers];
    }

    glDeleteBuffers((GLsizei)pn, (const GLuint*)(ptr_pbuffers));
    
    
}
void func_org_mini_gl_GL_glDeleteFramebuffers__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *pframebuffers, s32 offset_pframebuffers) {
    
    __refer ptr_pframebuffers = (__refer)(intptr_t) offset_pframebuffers;
    if(pframebuffers) {
        s32 bytes_pframebuffers = data_type_bytes[pframebuffers->prop.arr_type] * offset_pframebuffers;
        ptr_pframebuffers = &pframebuffers->prop.as_s8_arr[bytes_pframebuffers];
    }

    glDeleteFramebuffers((GLsizei)pn, (const GLuint*)(ptr_pframebuffers));
    
    
}
void func_org_mini_gl_GL_glDeleteProgram__I_V(JThreadRuntime *runtime, s32 pprogram) {
    

    glDeleteProgram((GLuint)pprogram);
    
    
}
void func_org_mini_gl_GL_glDeleteRenderbuffers__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *prenderbuffers, s32 offset_prenderbuffers) {
    
    __refer ptr_prenderbuffers = (__refer)(intptr_t) offset_prenderbuffers;
    if(prenderbuffers) {
        s32 bytes_prenderbuffers = data_type_bytes[prenderbuffers->prop.arr_type] * offset_prenderbuffers;
        ptr_prenderbuffers = &prenderbuffers->prop.as_s8_arr[bytes_prenderbuffers];
    }

    glDeleteRenderbuffers((GLsizei)pn, (const GLuint*)(ptr_prenderbuffers));
    
    
}
void func_org_mini_gl_GL_glDeleteShader__I_V(JThreadRuntime *runtime, s32 pshader) {
    

    glDeleteShader((GLuint)pshader);
    
    
}
void func_org_mini_gl_GL_glDeleteTextures__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *ptextures, s32 offset_ptextures) {
    
    __refer ptr_ptextures = (__refer)(intptr_t) offset_ptextures;
    if(ptextures) {
        s32 bytes_ptextures = data_type_bytes[ptextures->prop.arr_type] * offset_ptextures;
        ptr_ptextures = &ptextures->prop.as_s8_arr[bytes_ptextures];
    }

    glDeleteTextures((GLsizei)pn, (const GLuint*)(ptr_ptextures));
    
    
}
void func_org_mini_gl_GL_glDepthFunc__I_V(JThreadRuntime *runtime, s32 pfunc) {
    

    glDepthFunc((GLenum)pfunc);
    
    
}
void func_org_mini_gl_GL_glDepthMask__I_V(JThreadRuntime *runtime, s32 pflag) {
    

    glDepthMask((GLboolean)pflag);
    
    
}
void func_org_mini_gl_GL_glDepthRangef__FF_V(JThreadRuntime *runtime, f32 pn, f32 pf) {
    

    glDepthRangef((GLfloat)pn, (GLfloat)pf);
    
    
}
void func_org_mini_gl_GL_glDetachShader__II_V(JThreadRuntime *runtime, s32 pprogram, s32 pshader) {
    

    glDetachShader((GLuint)pprogram, (GLuint)pshader);
    
    
}
void func_org_mini_gl_GL_glDisable__I_V(JThreadRuntime *runtime, s32 pcap) {
    

    glDisable((GLenum)pcap);
    
    
}
void func_org_mini_gl_GL_glDisableVertexAttribArray__I_V(JThreadRuntime *runtime, s32 pindex) {
    

    glDisableVertexAttribArray((GLuint)pindex);
    
    
}
void func_org_mini_gl_GL_glDrawArrays__III_V(JThreadRuntime *runtime, s32 pmode, s32 pfirst, s32 pcount) {
    

    glDrawArrays((GLenum)pmode, (GLint)pfirst, (GLsizei)pcount);
    
    
}
void func_org_mini_gl_GL_glDrawElements__IIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 pmode, s32 pcount, s32 ptype, struct java_lang_Object *pindices, s32 offset_pindices) {
    
    __refer ptr_pindices = (__refer)(intptr_t) offset_pindices;
    if(pindices) {
        s32 bytes_pindices = data_type_bytes[pindices->prop.arr_type] * offset_pindices;
        ptr_pindices = &pindices->prop.as_s8_arr[bytes_pindices];
    }

    glDrawElements((GLenum)pmode, (GLsizei)pcount, (GLenum)ptype, (const void*)(ptr_pindices));
    
    
}
void func_org_mini_gl_GL_glEnable__I_V(JThreadRuntime *runtime, s32 pcap) {
    

    glEnable((GLenum)pcap);
    
    
}
void func_org_mini_gl_GL_glEnableVertexAttribArray__I_V(JThreadRuntime *runtime, s32 pindex) {
    

    glEnableVertexAttribArray((GLuint)pindex);
    
    
}
void func_org_mini_gl_GL_glFinish___V(JThreadRuntime *runtime) {
    

    glFinish();
    
    
}
void func_org_mini_gl_GL_glFlush___V(JThreadRuntime *runtime) {
    

    glFlush();
    
    
}
void func_org_mini_gl_GL_glFramebufferRenderbuffer__IIII_V(JThreadRuntime *runtime, s32 ptarget, s32 pattachment, s32 prenderbuffertarget, s32 prenderbuffer) {
    

    glFramebufferRenderbuffer((GLenum)ptarget, (GLenum)pattachment, (GLenum)prenderbuffertarget, (GLuint)prenderbuffer);
    
    
}
void func_org_mini_gl_GL_glFramebufferTexture2D__IIIII_V(JThreadRuntime *runtime, s32 ptarget, s32 pattachment, s32 ptextarget, s32 ptexture, s32 plevel) {
    

    glFramebufferTexture2D((GLenum)ptarget, (GLenum)pattachment, (GLenum)ptextarget, (GLuint)ptexture, (GLint)plevel);
    
    
}
void func_org_mini_gl_GL_glFrontFace__I_V(JThreadRuntime *runtime, s32 pmode) {
    

    glFrontFace((GLenum)pmode);
    
    
}
void func_org_mini_gl_GL_glGenBuffers__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *pbuffers, s32 offset_pbuffers) {
    
    __refer ptr_pbuffers = (__refer)(intptr_t) offset_pbuffers;
    if(pbuffers) {
        s32 bytes_pbuffers = data_type_bytes[pbuffers->prop.arr_type] * offset_pbuffers;
        ptr_pbuffers = &pbuffers->prop.as_s8_arr[bytes_pbuffers];
    }

    glGenBuffers((GLsizei)pn, (GLuint*)(ptr_pbuffers));
    
    
}
void func_org_mini_gl_GL_glGenerateMipmap__I_V(JThreadRuntime *runtime, s32 ptarget) {
    

    glGenerateMipmap((GLenum)ptarget);
    
    
}
void func_org_mini_gl_GL_glGenFramebuffers__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *pframebuffers, s32 offset_pframebuffers) {
    
    __refer ptr_pframebuffers = (__refer)(intptr_t) offset_pframebuffers;
    if(pframebuffers) {
        s32 bytes_pframebuffers = data_type_bytes[pframebuffers->prop.arr_type] * offset_pframebuffers;
        ptr_pframebuffers = &pframebuffers->prop.as_s8_arr[bytes_pframebuffers];
    }

    glGenFramebuffers((GLsizei)pn, (GLuint*)(ptr_pframebuffers));
    
    
}
void func_org_mini_gl_GL_glGenRenderbuffers__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *prenderbuffers, s32 offset_prenderbuffers) {
    
    __refer ptr_prenderbuffers = (__refer)(intptr_t) offset_prenderbuffers;
    if(prenderbuffers) {
        s32 bytes_prenderbuffers = data_type_bytes[prenderbuffers->prop.arr_type] * offset_prenderbuffers;
        ptr_prenderbuffers = &prenderbuffers->prop.as_s8_arr[bytes_prenderbuffers];
    }

    glGenRenderbuffers((GLsizei)pn, (GLuint*)(ptr_prenderbuffers));
    
    
}
void func_org_mini_gl_GL_glGenTextures__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *ptextures, s32 offset_ptextures) {
    
    __refer ptr_ptextures = (__refer)(intptr_t) offset_ptextures;
    if(ptextures) {
        s32 bytes_ptextures = data_type_bytes[ptextures->prop.arr_type] * offset_ptextures;
        ptr_ptextures = &ptextures->prop.as_s8_arr[bytes_ptextures];
    }

    glGenTextures((GLsizei)pn, (GLuint*)(ptr_ptextures));
    
    
}
void func_org_mini_gl_GL_glGetActiveAttrib__III_3II_3II_3II_3B_V(JThreadRuntime *runtime, s32 pprogram, s32 pindex, s32 pbufSize, JArray *plength, s32 offset_plength, JArray *psize, s32 offset_psize, JArray *ptype, s32 offset_ptype, JArray *pname) {
    
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }
    __refer ptr_psize = (__refer)(intptr_t) offset_psize;
    if(psize) {
        s32 bytes_psize = data_type_bytes[psize->prop.arr_type] * offset_psize;
        ptr_psize = &psize->prop.as_s8_arr[bytes_psize];
    }
    __refer ptr_ptype = (__refer)(intptr_t) offset_ptype;
    if(ptype) {
        s32 bytes_ptype = data_type_bytes[ptype->prop.arr_type] * offset_ptype;
        ptr_ptype = &ptype->prop.as_s8_arr[bytes_ptype];
    }
    s32 offset_pname = 0;    __refer ptr_pname = (__refer)(intptr_t) offset_pname;
    if(pname) {
        s32 bytes_pname = data_type_bytes[pname->prop.arr_type] * offset_pname;
        ptr_pname = &pname->prop.as_s8_arr[bytes_pname];
    }

    glGetActiveAttrib((GLuint)pprogram, (GLuint)pindex, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLint*)(ptr_psize), (GLenum*)(ptr_ptype), (GLchar*)(ptr_pname));
    
    
}
void func_org_mini_gl_GL_glGetActiveUniform__III_3II_3II_3II_3B_V(JThreadRuntime *runtime, s32 pprogram, s32 pindex, s32 pbufSize, JArray *plength, s32 offset_plength, JArray *psize, s32 offset_psize, JArray *ptype, s32 offset_ptype, JArray *pname) {
    
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }
    __refer ptr_psize = (__refer)(intptr_t) offset_psize;
    if(psize) {
        s32 bytes_psize = data_type_bytes[psize->prop.arr_type] * offset_psize;
        ptr_psize = &psize->prop.as_s8_arr[bytes_psize];
    }
    __refer ptr_ptype = (__refer)(intptr_t) offset_ptype;
    if(ptype) {
        s32 bytes_ptype = data_type_bytes[ptype->prop.arr_type] * offset_ptype;
        ptr_ptype = &ptype->prop.as_s8_arr[bytes_ptype];
    }
    s32 offset_pname = 0;    __refer ptr_pname = (__refer)(intptr_t) offset_pname;
    if(pname) {
        s32 bytes_pname = data_type_bytes[pname->prop.arr_type] * offset_pname;
        ptr_pname = &pname->prop.as_s8_arr[bytes_pname];
    }

    glGetActiveUniform((GLuint)pprogram, (GLuint)pindex, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLint*)(ptr_psize), (GLenum*)(ptr_ptype), (GLchar*)(ptr_pname));
    
    
}
void func_org_mini_gl_GL_glGetAttachedShaders__II_3II_3II_V(JThreadRuntime *runtime, s32 pprogram, s32 pmaxCount, JArray *pcount, s32 offset_pcount, JArray *pshaders, s32 offset_pshaders) {
    
    __refer ptr_pcount = (__refer)(intptr_t) offset_pcount;
    if(pcount) {
        s32 bytes_pcount = data_type_bytes[pcount->prop.arr_type] * offset_pcount;
        ptr_pcount = &pcount->prop.as_s8_arr[bytes_pcount];
    }
    __refer ptr_pshaders = (__refer)(intptr_t) offset_pshaders;
    if(pshaders) {
        s32 bytes_pshaders = data_type_bytes[pshaders->prop.arr_type] * offset_pshaders;
        ptr_pshaders = &pshaders->prop.as_s8_arr[bytes_pshaders];
    }

    glGetAttachedShaders((GLuint)pprogram, (GLsizei)pmaxCount, (GLsizei*)(ptr_pcount), (GLuint*)(ptr_pshaders));
    
    
}
s32 func_org_mini_gl_GL_glGetAttribLocation__I_3B_I(JThreadRuntime *runtime, s32 pprogram, JArray *pname) {
    
    s32 offset_pname = 0;    __refer ptr_pname = (__refer)(intptr_t) offset_pname;
    if(pname) {
        s32 bytes_pname = data_type_bytes[pname->prop.arr_type] * offset_pname;
        ptr_pname = &pname->prop.as_s8_arr[bytes_pname];
    }

    GLint _re_val = glGetAttribLocation((GLuint)pprogram, (const GLchar*)(ptr_pname));
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glGetBooleanv__I_3II_V(JThreadRuntime *runtime, s32 ppname, JArray *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glGetBooleanv((GLenum)ppname, (GLboolean*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glGetBufferParameteriv__II_3II_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetBufferParameteriv((GLenum)ptarget, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
s32 func_org_mini_gl_GL_glGetError___I(JThreadRuntime *runtime) {
    

    GLenum _re_val = glGetError();
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glGetFloatv__I_3FI_V(JThreadRuntime *runtime, s32 ppname, JArray *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glGetFloatv((GLenum)ppname, (GLfloat*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glGetFramebufferAttachmentParameteriv__III_3II_V(JThreadRuntime *runtime, s32 ptarget, s32 pattachment, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetFramebufferAttachmentParameteriv((GLenum)ptarget, (GLenum)pattachment, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetIntegerv__I_3II_V(JThreadRuntime *runtime, s32 ppname, JArray *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glGetIntegerv((GLenum)ppname, (GLint*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glGetProgramiv__II_3II_V(JThreadRuntime *runtime, s32 pprogram, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetProgramiv((GLuint)pprogram, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetProgramInfoLog__II_3II_3B_V(JThreadRuntime *runtime, s32 pprogram, s32 pbufSize, JArray *plength, s32 offset_plength, JArray *pinfoLog) {
    
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }
    s32 offset_pinfoLog = 0;    __refer ptr_pinfoLog = (__refer)(intptr_t) offset_pinfoLog;
    if(pinfoLog) {
        s32 bytes_pinfoLog = data_type_bytes[pinfoLog->prop.arr_type] * offset_pinfoLog;
        ptr_pinfoLog = &pinfoLog->prop.as_s8_arr[bytes_pinfoLog];
    }

    glGetProgramInfoLog((GLuint)pprogram, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLchar*)(ptr_pinfoLog));
    
    
}
void func_org_mini_gl_GL_glGetRenderbufferParameteriv__II_3II_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetRenderbufferParameteriv((GLenum)ptarget, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetShaderiv__II_3II_V(JThreadRuntime *runtime, s32 pshader, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetShaderiv((GLuint)pshader, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetShaderInfoLog__II_3II_3B_V(JThreadRuntime *runtime, s32 pshader, s32 pbufSize, JArray *plength, s32 offset_plength, JArray *pinfoLog) {
    
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }
    s32 offset_pinfoLog = 0;    __refer ptr_pinfoLog = (__refer)(intptr_t) offset_pinfoLog;
    if(pinfoLog) {
        s32 bytes_pinfoLog = data_type_bytes[pinfoLog->prop.arr_type] * offset_pinfoLog;
        ptr_pinfoLog = &pinfoLog->prop.as_s8_arr[bytes_pinfoLog];
    }

    glGetShaderInfoLog((GLuint)pshader, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLchar*)(ptr_pinfoLog));
    
    
}
void func_org_mini_gl_GL_glGetShaderPrecisionFormat__II_3II_3II_V(JThreadRuntime *runtime, s32 pshadertype, s32 pprecisiontype, JArray *prange, s32 offset_prange, JArray *pprecision, s32 offset_pprecision) {
    
    __refer ptr_prange = (__refer)(intptr_t) offset_prange;
    if(prange) {
        s32 bytes_prange = data_type_bytes[prange->prop.arr_type] * offset_prange;
        ptr_prange = &prange->prop.as_s8_arr[bytes_prange];
    }
    __refer ptr_pprecision = (__refer)(intptr_t) offset_pprecision;
    if(pprecision) {
        s32 bytes_pprecision = data_type_bytes[pprecision->prop.arr_type] * offset_pprecision;
        ptr_pprecision = &pprecision->prop.as_s8_arr[bytes_pprecision];
    }

    glGetShaderPrecisionFormat((GLenum)pshadertype, (GLenum)pprecisiontype, (GLint*)(ptr_prange), (GLint*)(ptr_pprecision));
    
    
}
void func_org_mini_gl_GL_glGetShaderSource__II_3II_3B_V(JThreadRuntime *runtime, s32 pshader, s32 pbufSize, JArray *plength, s32 offset_plength, JArray *psource) {
    
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }
    s32 offset_psource = 0;    __refer ptr_psource = (__refer)(intptr_t) offset_psource;
    if(psource) {
        s32 bytes_psource = data_type_bytes[psource->prop.arr_type] * offset_psource;
        ptr_psource = &psource->prop.as_s8_arr[bytes_psource];
    }

    glGetShaderSource((GLuint)pshader, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLchar*)(ptr_psource));
    
    
}
JArray * func_org_mini_gl_GL_glGetString__I__3B(JThreadRuntime *runtime, s32 pname) {
    

    const GLubyte* _re_val = glGetString((GLenum)pname);
    c8* _ptr_re_val = (c8*)_re_val;
    if (_ptr_re_val) {
        s32 bytes = strlen(_ptr_re_val);
        s32 j_t_bytes = sizeof(c8) * bytes;
        JArray *_arr = multi_array_create_by_typename(runtime, &j_t_bytes, 1, "[B");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , j_t_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}
void func_org_mini_gl_GL_glGetTexParameterfv__II_3FI_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetTexParameterfv((GLenum)ptarget, (GLenum)ppname, (GLfloat*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetTexParameteriv__II_3II_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetTexParameteriv((GLenum)ptarget, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetUniformfv__II_3FI_V(JThreadRuntime *runtime, s32 pprogram, s32 plocation, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetUniformfv((GLuint)pprogram, (GLint)plocation, (GLfloat*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetUniformiv__II_3II_V(JThreadRuntime *runtime, s32 pprogram, s32 plocation, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetUniformiv((GLuint)pprogram, (GLint)plocation, (GLint*)(ptr_pparams));
    
    
}
s32 func_org_mini_gl_GL_glGetUniformLocation__I_3B_I(JThreadRuntime *runtime, s32 pprogram, JArray *pname) {
    
    s32 offset_pname = 0;    __refer ptr_pname = (__refer)(intptr_t) offset_pname;
    if(pname) {
        s32 bytes_pname = data_type_bytes[pname->prop.arr_type] * offset_pname;
        ptr_pname = &pname->prop.as_s8_arr[bytes_pname];
    }

    GLint _re_val = glGetUniformLocation((GLuint)pprogram, (const GLchar*)(ptr_pname));
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glGetVertexAttribfv__II_3FI_V(JThreadRuntime *runtime, s32 pindex, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetVertexAttribfv((GLuint)pindex, (GLenum)ppname, (GLfloat*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetVertexAttribiv__II_3II_V(JThreadRuntime *runtime, s32 pindex, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetVertexAttribiv((GLuint)pindex, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetVertexAttribPointerv__II_3Ljava_lang_Object_2_V(JThreadRuntime *runtime, s32 pindex, s32 ppname, JArray *ppointer) {
    

    glGetVertexAttribPointerv((GLuint)pindex, (GLenum)ppname, (void**)(ppointer->prop.as_obj_arr));
    
    
}
void func_org_mini_gl_GL_glHint__II_V(JThreadRuntime *runtime, s32 ptarget, s32 pmode) {
    

    glHint((GLenum)ptarget, (GLenum)pmode);
    
    
}
s32 func_org_mini_gl_GL_glIsBuffer__I_I(JThreadRuntime *runtime, s32 pbuffer) {
    

    GLboolean _re_val = glIsBuffer((GLuint)pbuffer);
    return *((s32*)&_re_val);
    
}
s32 func_org_mini_gl_GL_glIsEnabled__I_I(JThreadRuntime *runtime, s32 pcap) {
    

    GLboolean _re_val = glIsEnabled((GLenum)pcap);
    return *((s32*)&_re_val);
    
}
s32 func_org_mini_gl_GL_glIsFramebuffer__I_I(JThreadRuntime *runtime, s32 pframebuffer) {
    

    GLboolean _re_val = glIsFramebuffer((GLuint)pframebuffer);
    return *((s32*)&_re_val);
    
}
s32 func_org_mini_gl_GL_glIsProgram__I_I(JThreadRuntime *runtime, s32 pprogram) {
    

    GLboolean _re_val = glIsProgram((GLuint)pprogram);
    return *((s32*)&_re_val);
    
}
s32 func_org_mini_gl_GL_glIsRenderbuffer__I_I(JThreadRuntime *runtime, s32 prenderbuffer) {
    

    GLboolean _re_val = glIsRenderbuffer((GLuint)prenderbuffer);
    return *((s32*)&_re_val);
    
}
s32 func_org_mini_gl_GL_glIsShader__I_I(JThreadRuntime *runtime, s32 pshader) {
    

    GLboolean _re_val = glIsShader((GLuint)pshader);
    return *((s32*)&_re_val);
    
}
s32 func_org_mini_gl_GL_glIsTexture__I_I(JThreadRuntime *runtime, s32 ptexture) {
    

    GLboolean _re_val = glIsTexture((GLuint)ptexture);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glLineWidth__F_V(JThreadRuntime *runtime, f32 pwidth) {
    

    glLineWidth((GLfloat)pwidth);
    
    
}
void func_org_mini_gl_GL_glLinkProgram__I_V(JThreadRuntime *runtime, s32 pprogram) {
    

    glLinkProgram((GLuint)pprogram);
    
    
}
void func_org_mini_gl_GL_glPixelStorei__II_V(JThreadRuntime *runtime, s32 ppname, s32 pparam) {
    

    glPixelStorei((GLenum)ppname, (GLint)pparam);
    
    
}
void func_org_mini_gl_GL_glPolygonOffset__FF_V(JThreadRuntime *runtime, f32 pfactor, f32 punits) {
    

    glPolygonOffset((GLfloat)pfactor, (GLfloat)punits);
    
    
}
void func_org_mini_gl_GL_glReadPixels__IIIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 px, s32 py, s32 pwidth, s32 pheight, s32 pformat, s32 ptype, struct java_lang_Object *ppixels, s32 offset_ppixels) {
    
    __refer ptr_ppixels = (__refer)(intptr_t) offset_ppixels;
    if(ppixels) {
        s32 bytes_ppixels = data_type_bytes[ppixels->prop.arr_type] * offset_ppixels;
        ptr_ppixels = &ppixels->prop.as_s8_arr[bytes_ppixels];
    }

    glReadPixels((GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight, (GLenum)pformat, (GLenum)ptype, (void*)(ptr_ppixels));
    
    
}
void func_org_mini_gl_GL_glReleaseShaderCompiler___V(JThreadRuntime *runtime) {
    

    glReleaseShaderCompiler();
    
    
}
void func_org_mini_gl_GL_glRenderbufferStorage__IIII_V(JThreadRuntime *runtime, s32 ptarget, s32 pinternalformat, s32 pwidth, s32 pheight) {
    

    glRenderbufferStorage((GLenum)ptarget, (GLenum)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight);
    
    
}
void func_org_mini_gl_GL_glSampleCoverage__FI_V(JThreadRuntime *runtime, f32 pvalue, s32 pinvert) {
    

    glSampleCoverage((GLfloat)pvalue, (GLboolean)pinvert);
    
    
}
void func_org_mini_gl_GL_glScissor__IIII_V(JThreadRuntime *runtime, s32 px, s32 py, s32 pwidth, s32 pheight) {
    

    glScissor((GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight);
    
    
}
void func_org_mini_gl_GL_glShaderBinary__I_3IIILjava_lang_Object_2II_V(JThreadRuntime *runtime, s32 pcount, JArray *pshaders, s32 offset_pshaders, s32 pbinaryformat, struct java_lang_Object *pbinary, s32 offset_pbinary, s32 plength) {
    
    __refer ptr_pshaders = (__refer)(intptr_t) offset_pshaders;
    if(pshaders) {
        s32 bytes_pshaders = data_type_bytes[pshaders->prop.arr_type] * offset_pshaders;
        ptr_pshaders = &pshaders->prop.as_s8_arr[bytes_pshaders];
    }
    __refer ptr_pbinary = (__refer)(intptr_t) offset_pbinary;
    if(pbinary) {
        s32 bytes_pbinary = data_type_bytes[pbinary->prop.arr_type] * offset_pbinary;
        ptr_pbinary = &pbinary->prop.as_s8_arr[bytes_pbinary];
    }

    glShaderBinary((GLsizei)pcount, (const GLuint*)(ptr_pshaders), (GLenum)pbinaryformat, (const void*)(ptr_pbinary), (GLsizei)plength);
    
    
}
void func_org_mini_gl_GL_glShaderSource__II_3_3B_3II_V(JThreadRuntime *runtime, s32 pshader, s32 pcount, JArray *pstring, JArray *plength, s32 offset_plength) {
    
    __refer ptr_pstring[pstring->prop.arr_length];
    s32 i;for(i=0;i<pstring->prop.arr_length;i++){
        JArray *arr_pstring = (JArray *)pstring->prop.as_obj_arr[i];
        ptr_pstring[i] = arr_pstring->prop.as_c8_arr;
    }
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }

    glShaderSource((GLuint)pshader, (GLsizei)pcount, (const GLchar*const*)(ptr_pstring), (const GLint*)(ptr_plength));
    
    
}
void func_org_mini_gl_GL_glStencilFunc__III_V(JThreadRuntime *runtime, s32 pfunc, s32 pref, s32 pmask) {
    

    glStencilFunc((GLenum)pfunc, (GLint)pref, (GLuint)pmask);
    
    
}
void func_org_mini_gl_GL_glStencilFuncSeparate__IIII_V(JThreadRuntime *runtime, s32 pface, s32 pfunc, s32 pref, s32 pmask) {
    

    glStencilFuncSeparate((GLenum)pface, (GLenum)pfunc, (GLint)pref, (GLuint)pmask);
    
    
}
void func_org_mini_gl_GL_glStencilMask__I_V(JThreadRuntime *runtime, s32 pmask) {
    

    glStencilMask((GLuint)pmask);
    
    
}
void func_org_mini_gl_GL_glStencilMaskSeparate__II_V(JThreadRuntime *runtime, s32 pface, s32 pmask) {
    

    glStencilMaskSeparate((GLenum)pface, (GLuint)pmask);
    
    
}
void func_org_mini_gl_GL_glStencilOp__III_V(JThreadRuntime *runtime, s32 pfail, s32 pzfail, s32 pzpass) {
    

    glStencilOp((GLenum)pfail, (GLenum)pzfail, (GLenum)pzpass);
    
    
}
void func_org_mini_gl_GL_glStencilOpSeparate__IIII_V(JThreadRuntime *runtime, s32 pface, s32 psfail, s32 pdpfail, s32 pdppass) {
    

    glStencilOpSeparate((GLenum)pface, (GLenum)psfail, (GLenum)pdpfail, (GLenum)pdppass);
    
    
}
void func_org_mini_gl_GL_glTexImage2D__IIIIIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pinternalformat, s32 pwidth, s32 pheight, s32 pborder, s32 pformat, s32 ptype, struct java_lang_Object *ppixels, s32 offset_ppixels) {
    
    __refer ptr_ppixels = (__refer)(intptr_t) offset_ppixels;
    if(ppixels) {
        s32 bytes_ppixels = data_type_bytes[ppixels->prop.arr_type] * offset_ppixels;
        ptr_ppixels = &ppixels->prop.as_s8_arr[bytes_ppixels];
    }

    glTexImage2D((GLenum)ptarget, (GLint)plevel, (GLint)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight, (GLint)pborder, (GLenum)pformat, (GLenum)ptype, (const void*)(ptr_ppixels));
    
    
}
void func_org_mini_gl_GL_glTexParameterf__IIF_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, f32 pparam) {
    

    glTexParameterf((GLenum)ptarget, (GLenum)ppname, (GLfloat)pparam);
    
    
}
void func_org_mini_gl_GL_glTexParameterfv__II_3FI_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glTexParameterfv((GLenum)ptarget, (GLenum)ppname, (const GLfloat*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glTexParameteri__III_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, s32 pparam) {
    

    glTexParameteri((GLenum)ptarget, (GLenum)ppname, (GLint)pparam);
    
    
}
void func_org_mini_gl_GL_glTexParameteriv__II_3II_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glTexParameteriv((GLenum)ptarget, (GLenum)ppname, (const GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glTexSubImage2D__IIIIIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pxoffset, s32 pyoffset, s32 pwidth, s32 pheight, s32 pformat, s32 ptype, struct java_lang_Object *ppixels, s32 offset_ppixels) {
    
    __refer ptr_ppixels = (__refer)(intptr_t) offset_ppixels;
    if(ppixels) {
        s32 bytes_ppixels = data_type_bytes[ppixels->prop.arr_type] * offset_ppixels;
        ptr_ppixels = &ppixels->prop.as_s8_arr[bytes_ppixels];
    }

    glTexSubImage2D((GLenum)ptarget, (GLint)plevel, (GLint)pxoffset, (GLint)pyoffset, (GLsizei)pwidth, (GLsizei)pheight, (GLenum)pformat, (GLenum)ptype, (const void*)(ptr_ppixels));
    
    
}
void func_org_mini_gl_GL_glUniform1f__IF_V(JThreadRuntime *runtime, s32 plocation, f32 pv0) {
    

    glUniform1f((GLint)plocation, (GLfloat)pv0);
    
    
}
void func_org_mini_gl_GL_glUniform1fv__II_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform1fv((GLint)plocation, (GLsizei)pcount, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform1i__II_V(JThreadRuntime *runtime, s32 plocation, s32 pv0) {
    

    glUniform1i((GLint)plocation, (GLint)pv0);
    
    
}
void func_org_mini_gl_GL_glUniform1iv__II_3II_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform1iv((GLint)plocation, (GLsizei)pcount, (const GLint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform2f__IFF_V(JThreadRuntime *runtime, s32 plocation, f32 pv0, f32 pv1) {
    

    glUniform2f((GLint)plocation, (GLfloat)pv0, (GLfloat)pv1);
    
    
}
void func_org_mini_gl_GL_glUniform2fv__II_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform2fv((GLint)plocation, (GLsizei)pcount, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform2i__III_V(JThreadRuntime *runtime, s32 plocation, s32 pv0, s32 pv1) {
    

    glUniform2i((GLint)plocation, (GLint)pv0, (GLint)pv1);
    
    
}
void func_org_mini_gl_GL_glUniform2iv__II_3II_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform2iv((GLint)plocation, (GLsizei)pcount, (const GLint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform3f__IFFF_V(JThreadRuntime *runtime, s32 plocation, f32 pv0, f32 pv1, f32 pv2) {
    

    glUniform3f((GLint)plocation, (GLfloat)pv0, (GLfloat)pv1, (GLfloat)pv2);
    
    
}
void func_org_mini_gl_GL_glUniform3fv__II_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform3fv((GLint)plocation, (GLsizei)pcount, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform3i__IIII_V(JThreadRuntime *runtime, s32 plocation, s32 pv0, s32 pv1, s32 pv2) {
    

    glUniform3i((GLint)plocation, (GLint)pv0, (GLint)pv1, (GLint)pv2);
    
    
}
void func_org_mini_gl_GL_glUniform3iv__II_3II_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform3iv((GLint)plocation, (GLsizei)pcount, (const GLint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform4f__IFFFF_V(JThreadRuntime *runtime, s32 plocation, f32 pv0, f32 pv1, f32 pv2, f32 pv3) {
    

    glUniform4f((GLint)plocation, (GLfloat)pv0, (GLfloat)pv1, (GLfloat)pv2, (GLfloat)pv3);
    
    
}
void func_org_mini_gl_GL_glUniform4fv__II_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform4fv((GLint)plocation, (GLsizei)pcount, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform4i__IIIII_V(JThreadRuntime *runtime, s32 plocation, s32 pv0, s32 pv1, s32 pv2, s32 pv3) {
    

    glUniform4i((GLint)plocation, (GLint)pv0, (GLint)pv1, (GLint)pv2, (GLint)pv3);
    
    
}
void func_org_mini_gl_GL_glUniform4iv__II_3II_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform4iv((GLint)plocation, (GLsizei)pcount, (const GLint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniformMatrix2fv__III_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, s32 ptranspose, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniformMatrix2fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniformMatrix3fv__III_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, s32 ptranspose, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniformMatrix3fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniformMatrix4fv__III_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, s32 ptranspose, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniformMatrix4fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUseProgram__I_V(JThreadRuntime *runtime, s32 pprogram) {
    

    glUseProgram((GLuint)pprogram);
    
    
}
void func_org_mini_gl_GL_glValidateProgram__I_V(JThreadRuntime *runtime, s32 pprogram) {
    

    glValidateProgram((GLuint)pprogram);
    
    
}
void func_org_mini_gl_GL_glVertexAttrib1f__IF_V(JThreadRuntime *runtime, s32 pindex, f32 px) {
    

    glVertexAttrib1f((GLuint)pindex, (GLfloat)px);
    
    
}
void func_org_mini_gl_GL_glVertexAttrib1fv__I_3FI_V(JThreadRuntime *runtime, s32 pindex, JArray *pv, s32 offset_pv) {
    
    __refer ptr_pv = (__refer)(intptr_t) offset_pv;
    if(pv) {
        s32 bytes_pv = data_type_bytes[pv->prop.arr_type] * offset_pv;
        ptr_pv = &pv->prop.as_s8_arr[bytes_pv];
    }

    glVertexAttrib1fv((GLuint)pindex, (const GLfloat*)(ptr_pv));
    
    
}
void func_org_mini_gl_GL_glVertexAttrib2f__IFF_V(JThreadRuntime *runtime, s32 pindex, f32 px, f32 py) {
    

    glVertexAttrib2f((GLuint)pindex, (GLfloat)px, (GLfloat)py);
    
    
}
void func_org_mini_gl_GL_glVertexAttrib2fv__I_3FI_V(JThreadRuntime *runtime, s32 pindex, JArray *pv, s32 offset_pv) {
    
    __refer ptr_pv = (__refer)(intptr_t) offset_pv;
    if(pv) {
        s32 bytes_pv = data_type_bytes[pv->prop.arr_type] * offset_pv;
        ptr_pv = &pv->prop.as_s8_arr[bytes_pv];
    }

    glVertexAttrib2fv((GLuint)pindex, (const GLfloat*)(ptr_pv));
    
    
}
void func_org_mini_gl_GL_glVertexAttrib3f__IFFF_V(JThreadRuntime *runtime, s32 pindex, f32 px, f32 py, f32 pz) {
    

    glVertexAttrib3f((GLuint)pindex, (GLfloat)px, (GLfloat)py, (GLfloat)pz);
    
    
}
void func_org_mini_gl_GL_glVertexAttrib3fv__I_3FI_V(JThreadRuntime *runtime, s32 pindex, JArray *pv, s32 offset_pv) {
    
    __refer ptr_pv = (__refer)(intptr_t) offset_pv;
    if(pv) {
        s32 bytes_pv = data_type_bytes[pv->prop.arr_type] * offset_pv;
        ptr_pv = &pv->prop.as_s8_arr[bytes_pv];
    }

    glVertexAttrib3fv((GLuint)pindex, (const GLfloat*)(ptr_pv));
    
    
}
void func_org_mini_gl_GL_glVertexAttrib4f__IFFFF_V(JThreadRuntime *runtime, s32 pindex, f32 px, f32 py, f32 pz, f32 pw) {
    

    glVertexAttrib4f((GLuint)pindex, (GLfloat)px, (GLfloat)py, (GLfloat)pz, (GLfloat)pw);
    
    
}
void func_org_mini_gl_GL_glVertexAttrib4fv__I_3FI_V(JThreadRuntime *runtime, s32 pindex, JArray *pv, s32 offset_pv) {
    
    __refer ptr_pv = (__refer)(intptr_t) offset_pv;
    if(pv) {
        s32 bytes_pv = data_type_bytes[pv->prop.arr_type] * offset_pv;
        ptr_pv = &pv->prop.as_s8_arr[bytes_pv];
    }

    glVertexAttrib4fv((GLuint)pindex, (const GLfloat*)(ptr_pv));
    
    
}
void func_org_mini_gl_GL_glVertexAttribPointer__IIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 pindex, s32 psize, s32 ptype, s32 pnormalized, s32 pstride, struct java_lang_Object *ppointer, s32 offset_ppointer) {
    
    __refer ptr_ppointer = (__refer)(intptr_t) offset_ppointer;
    if(ppointer) {
        s32 bytes_ppointer = data_type_bytes[ppointer->prop.arr_type] * offset_ppointer;
        ptr_ppointer = &ppointer->prop.as_s8_arr[bytes_ppointer];
    }

    glVertexAttribPointer((GLuint)pindex, (GLint)psize, (GLenum)ptype, (GLboolean)pnormalized, (GLsizei)pstride, (const void*)(ptr_ppointer));
    
    
}
void func_org_mini_gl_GL_glViewport__IIII_V(JThreadRuntime *runtime, s32 px, s32 py, s32 pwidth, s32 pheight) {
    

    glViewport((GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight);
    
    
}
void func_org_mini_gl_GL_glReadBuffer__I_V(JThreadRuntime *runtime, s32 psrc) {
    

    glReadBuffer((GLenum)psrc);
    
    
}
void func_org_mini_gl_GL_glDrawRangeElements__IIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 pmode, s32 pstart, s32 pend, s32 pcount, s32 ptype, struct java_lang_Object *pindices, s32 offset_pindices) {
    
    __refer ptr_pindices = (__refer)(intptr_t) offset_pindices;
    if(pindices) {
        s32 bytes_pindices = data_type_bytes[pindices->prop.arr_type] * offset_pindices;
        ptr_pindices = &pindices->prop.as_s8_arr[bytes_pindices];
    }

    glDrawRangeElements((GLenum)pmode, (GLuint)pstart, (GLuint)pend, (GLsizei)pcount, (GLenum)ptype, (const void*)(ptr_pindices));
    
    
}
void func_org_mini_gl_GL_glTexImage3D__IIIIIIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pinternalformat, s32 pwidth, s32 pheight, s32 pdepth, s32 pborder, s32 pformat, s32 ptype, struct java_lang_Object *ppixels, s32 offset_ppixels) {
    
    __refer ptr_ppixels = (__refer)(intptr_t) offset_ppixels;
    if(ppixels) {
        s32 bytes_ppixels = data_type_bytes[ppixels->prop.arr_type] * offset_ppixels;
        ptr_ppixels = &ppixels->prop.as_s8_arr[bytes_ppixels];
    }

    glTexImage3D((GLenum)ptarget, (GLint)plevel, (GLint)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight, (GLsizei)pdepth, (GLint)pborder, (GLenum)pformat, (GLenum)ptype, (const void*)(ptr_ppixels));
    
    
}
void func_org_mini_gl_GL_glTexSubImage3D__IIIIIIIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pxoffset, s32 pyoffset, s32 pzoffset, s32 pwidth, s32 pheight, s32 pdepth, s32 pformat, s32 ptype, struct java_lang_Object *ppixels, s32 offset_ppixels) {
    
    __refer ptr_ppixels = (__refer)(intptr_t) offset_ppixels;
    if(ppixels) {
        s32 bytes_ppixels = data_type_bytes[ppixels->prop.arr_type] * offset_ppixels;
        ptr_ppixels = &ppixels->prop.as_s8_arr[bytes_ppixels];
    }

    glTexSubImage3D((GLenum)ptarget, (GLint)plevel, (GLint)pxoffset, (GLint)pyoffset, (GLint)pzoffset, (GLsizei)pwidth, (GLsizei)pheight, (GLsizei)pdepth, (GLenum)pformat, (GLenum)ptype, (const void*)(ptr_ppixels));
    
    
}
void func_org_mini_gl_GL_glCopyTexSubImage3D__IIIIIIIII_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pxoffset, s32 pyoffset, s32 pzoffset, s32 px, s32 py, s32 pwidth, s32 pheight) {
    

    glCopyTexSubImage3D((GLenum)ptarget, (GLint)plevel, (GLint)pxoffset, (GLint)pyoffset, (GLint)pzoffset, (GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight);
    
    
}
void func_org_mini_gl_GL_glCompressedTexImage3D__IIIIIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pinternalformat, s32 pwidth, s32 pheight, s32 pdepth, s32 pborder, s32 pimageSize, struct java_lang_Object *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glCompressedTexImage3D((GLenum)ptarget, (GLint)plevel, (GLenum)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight, (GLsizei)pdepth, (GLint)pborder, (GLsizei)pimageSize, (const void*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glCompressedTexSubImage3D__IIIIIIIIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 ptarget, s32 plevel, s32 pxoffset, s32 pyoffset, s32 pzoffset, s32 pwidth, s32 pheight, s32 pdepth, s32 pformat, s32 pimageSize, struct java_lang_Object *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glCompressedTexSubImage3D((GLenum)ptarget, (GLint)plevel, (GLint)pxoffset, (GLint)pyoffset, (GLint)pzoffset, (GLsizei)pwidth, (GLsizei)pheight, (GLsizei)pdepth, (GLenum)pformat, (GLsizei)pimageSize, (const void*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glGenQueries__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *pids, s32 offset_pids) {
    
    __refer ptr_pids = (__refer)(intptr_t) offset_pids;
    if(pids) {
        s32 bytes_pids = data_type_bytes[pids->prop.arr_type] * offset_pids;
        ptr_pids = &pids->prop.as_s8_arr[bytes_pids];
    }

    glGenQueries((GLsizei)pn, (GLuint*)(ptr_pids));
    
    
}
void func_org_mini_gl_GL_glDeleteQueries__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *pids, s32 offset_pids) {
    
    __refer ptr_pids = (__refer)(intptr_t) offset_pids;
    if(pids) {
        s32 bytes_pids = data_type_bytes[pids->prop.arr_type] * offset_pids;
        ptr_pids = &pids->prop.as_s8_arr[bytes_pids];
    }

    glDeleteQueries((GLsizei)pn, (const GLuint*)(ptr_pids));
    
    
}
s32 func_org_mini_gl_GL_glIsQuery__I_I(JThreadRuntime *runtime, s32 pid) {
    

    GLboolean _re_val = glIsQuery((GLuint)pid);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glBeginQuery__II_V(JThreadRuntime *runtime, s32 ptarget, s32 pid) {
    

    glBeginQuery((GLenum)ptarget, (GLuint)pid);
    
    
}
void func_org_mini_gl_GL_glEndQuery__I_V(JThreadRuntime *runtime, s32 ptarget) {
    

    glEndQuery((GLenum)ptarget);
    
    
}
void func_org_mini_gl_GL_glGetQueryiv__II_3II_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetQueryiv((GLenum)ptarget, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetQueryObjectuiv__II_3II_V(JThreadRuntime *runtime, s32 pid, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetQueryObjectuiv((GLuint)pid, (GLenum)ppname, (GLuint*)(ptr_pparams));
    
    
}
s32 func_org_mini_gl_GL_glUnmapBuffer__I_I(JThreadRuntime *runtime, s32 ptarget) {
    

    GLboolean _re_val = glUnmapBuffer((GLenum)ptarget);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glGetBufferPointerv__II_3Ljava_lang_Object_2_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, JArray *pparams) {
    

    glGetBufferPointerv((GLenum)ptarget, (GLenum)ppname, (void**)(pparams->prop.as_obj_arr));
    
    
}
void func_org_mini_gl_GL_glDrawBuffers__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *pbufs, s32 offset_pbufs) {
    
    __refer ptr_pbufs = (__refer)(intptr_t) offset_pbufs;
    if(pbufs) {
        s32 bytes_pbufs = data_type_bytes[pbufs->prop.arr_type] * offset_pbufs;
        ptr_pbufs = &pbufs->prop.as_s8_arr[bytes_pbufs];
    }

    glDrawBuffers((GLsizei)pn, (const GLenum*)(ptr_pbufs));
    
    
}
void func_org_mini_gl_GL_glUniformMatrix2x3fv__III_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, s32 ptranspose, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniformMatrix2x3fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniformMatrix3x2fv__III_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, s32 ptranspose, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniformMatrix3x2fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniformMatrix2x4fv__III_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, s32 ptranspose, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniformMatrix2x4fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniformMatrix4x2fv__III_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, s32 ptranspose, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniformMatrix4x2fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniformMatrix3x4fv__III_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, s32 ptranspose, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniformMatrix3x4fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniformMatrix4x3fv__III_3FI_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, s32 ptranspose, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniformMatrix4x3fv((GLint)plocation, (GLsizei)pcount, (GLboolean)ptranspose, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glBlitFramebuffer__IIIIIIIIII_V(JThreadRuntime *runtime, s32 psrcX0, s32 psrcY0, s32 psrcX1, s32 psrcY1, s32 pdstX0, s32 pdstY0, s32 pdstX1, s32 pdstY1, s32 pmask, s32 pfilter) {
    

    glBlitFramebuffer((GLint)psrcX0, (GLint)psrcY0, (GLint)psrcX1, (GLint)psrcY1, (GLint)pdstX0, (GLint)pdstY0, (GLint)pdstX1, (GLint)pdstY1, (GLbitfield)pmask, (GLenum)pfilter);
    
    
}
void func_org_mini_gl_GL_glRenderbufferStorageMultisample__IIIII_V(JThreadRuntime *runtime, s32 ptarget, s32 psamples, s32 pinternalformat, s32 pwidth, s32 pheight) {
    

    glRenderbufferStorageMultisample((GLenum)ptarget, (GLsizei)psamples, (GLenum)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight);
    
    
}
void func_org_mini_gl_GL_glFramebufferTextureLayer__IIIII_V(JThreadRuntime *runtime, s32 ptarget, s32 pattachment, s32 ptexture, s32 plevel, s32 player) {
    

    glFramebufferTextureLayer((GLenum)ptarget, (GLenum)pattachment, (GLuint)ptexture, (GLint)plevel, (GLint)player);
    
    
}
s64 func_org_mini_gl_GL_glMapBufferRange__IJJI_J(JThreadRuntime *runtime, s32 ptarget, s64 poffset, s64 plength, s32 paccess) {
    

    void* _re_val = glMapBufferRange((GLenum)ptarget, (GLintptr)poffset, (GLsizeiptr)plength, (GLbitfield)paccess);
    return *((s64*)&_re_val);
    
}
void func_org_mini_gl_GL_glFlushMappedBufferRange__IJJ_V(JThreadRuntime *runtime, s32 ptarget, s64 poffset, s64 plength) {
    

    glFlushMappedBufferRange((GLenum)ptarget, (GLintptr)poffset, (GLsizeiptr)plength);
    
    
}
void func_org_mini_gl_GL_glBindVertexArray__I_V(JThreadRuntime *runtime, s32 parray) {
    

    glBindVertexArray((GLuint)parray);
    
    
}
void func_org_mini_gl_GL_glDeleteVertexArrays__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *parrays, s32 offset_parrays) {
    
    __refer ptr_parrays = (__refer)(intptr_t) offset_parrays;
    if(parrays) {
        s32 bytes_parrays = data_type_bytes[parrays->prop.arr_type] * offset_parrays;
        ptr_parrays = &parrays->prop.as_s8_arr[bytes_parrays];
    }

    glDeleteVertexArrays((GLsizei)pn, (const GLuint*)(ptr_parrays));
    
    
}
void func_org_mini_gl_GL_glGenVertexArrays__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *parrays, s32 offset_parrays) {
    
    __refer ptr_parrays = (__refer)(intptr_t) offset_parrays;
    if(parrays) {
        s32 bytes_parrays = data_type_bytes[parrays->prop.arr_type] * offset_parrays;
        ptr_parrays = &parrays->prop.as_s8_arr[bytes_parrays];
    }

    glGenVertexArrays((GLsizei)pn, (GLuint*)(ptr_parrays));
    
    
}
s32 func_org_mini_gl_GL_glIsVertexArray__I_I(JThreadRuntime *runtime, s32 parray) {
    

    GLboolean _re_val = glIsVertexArray((GLuint)parray);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glGetIntegeri_1v__II_3II_V(JThreadRuntime *runtime, s32 ptarget, s32 pindex, JArray *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glGetIntegeri_v((GLenum)ptarget, (GLuint)pindex, (GLint*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glBeginTransformFeedback__I_V(JThreadRuntime *runtime, s32 pprimitiveMode) {
    

    glBeginTransformFeedback((GLenum)pprimitiveMode);
    
    
}
void func_org_mini_gl_GL_glEndTransformFeedback___V(JThreadRuntime *runtime) {
    

    glEndTransformFeedback();
    
    
}
void func_org_mini_gl_GL_glBindBufferRange__IIIJJ_V(JThreadRuntime *runtime, s32 ptarget, s32 pindex, s32 pbuffer, s64 poffset, s64 psize) {
    

    glBindBufferRange((GLenum)ptarget, (GLuint)pindex, (GLuint)pbuffer, (GLintptr)poffset, (GLsizeiptr)psize);
    
    
}
void func_org_mini_gl_GL_glBindBufferBase__III_V(JThreadRuntime *runtime, s32 ptarget, s32 pindex, s32 pbuffer) {
    

    glBindBufferBase((GLenum)ptarget, (GLuint)pindex, (GLuint)pbuffer);
    
    
}
void func_org_mini_gl_GL_glTransformFeedbackVaryings__II_3_3BI_V(JThreadRuntime *runtime, s32 pprogram, s32 pcount, JArray *pvaryings, s32 pbufferMode) {
    
    __refer ptr_pvaryings[pvaryings->prop.arr_length];
    s32 i;for(i=0;i<pvaryings->prop.arr_length;i++){
        JArray *arr_pvaryings = (JArray *)pvaryings->prop.as_obj_arr[i];
        ptr_pvaryings[i] = arr_pvaryings->prop.as_c8_arr;
    }

    glTransformFeedbackVaryings((GLuint)pprogram, (GLsizei)pcount, (const GLchar*const*)(ptr_pvaryings), (GLenum)pbufferMode);
    
    
}
void func_org_mini_gl_GL_glGetTransformFeedbackVarying__III_3II_3II_3II_3B_V(JThreadRuntime *runtime, s32 pprogram, s32 pindex, s32 pbufSize, JArray *plength, s32 offset_plength, JArray *psize, s32 offset_psize, JArray *ptype, s32 offset_ptype, JArray *pname) {
    
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }
    __refer ptr_psize = (__refer)(intptr_t) offset_psize;
    if(psize) {
        s32 bytes_psize = data_type_bytes[psize->prop.arr_type] * offset_psize;
        ptr_psize = &psize->prop.as_s8_arr[bytes_psize];
    }
    __refer ptr_ptype = (__refer)(intptr_t) offset_ptype;
    if(ptype) {
        s32 bytes_ptype = data_type_bytes[ptype->prop.arr_type] * offset_ptype;
        ptr_ptype = &ptype->prop.as_s8_arr[bytes_ptype];
    }
    s32 offset_pname = 0;    __refer ptr_pname = (__refer)(intptr_t) offset_pname;
    if(pname) {
        s32 bytes_pname = data_type_bytes[pname->prop.arr_type] * offset_pname;
        ptr_pname = &pname->prop.as_s8_arr[bytes_pname];
    }

    glGetTransformFeedbackVarying((GLuint)pprogram, (GLuint)pindex, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLsizei*)(ptr_psize), (GLenum*)(ptr_ptype), (GLchar*)(ptr_pname));
    
    
}
void func_org_mini_gl_GL_glVertexAttribIPointer__IIIILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 pindex, s32 psize, s32 ptype, s32 pstride, struct java_lang_Object *ppointer, s32 offset_ppointer) {
    
    __refer ptr_ppointer = (__refer)(intptr_t) offset_ppointer;
    if(ppointer) {
        s32 bytes_ppointer = data_type_bytes[ppointer->prop.arr_type] * offset_ppointer;
        ptr_ppointer = &ppointer->prop.as_s8_arr[bytes_ppointer];
    }

    glVertexAttribIPointer((GLuint)pindex, (GLint)psize, (GLenum)ptype, (GLsizei)pstride, (const void*)(ptr_ppointer));
    
    
}
void func_org_mini_gl_GL_glGetVertexAttribIiv__II_3II_V(JThreadRuntime *runtime, s32 pindex, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetVertexAttribIiv((GLuint)pindex, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetVertexAttribIuiv__II_3II_V(JThreadRuntime *runtime, s32 pindex, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetVertexAttribIuiv((GLuint)pindex, (GLenum)ppname, (GLuint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glVertexAttribI4i__IIIII_V(JThreadRuntime *runtime, s32 pindex, s32 px, s32 py, s32 pz, s32 pw) {
    

    glVertexAttribI4i((GLuint)pindex, (GLint)px, (GLint)py, (GLint)pz, (GLint)pw);
    
    
}
void func_org_mini_gl_GL_glVertexAttribI4ui__IIIII_V(JThreadRuntime *runtime, s32 pindex, s32 px, s32 py, s32 pz, s32 pw) {
    

    glVertexAttribI4ui((GLuint)pindex, (GLuint)px, (GLuint)py, (GLuint)pz, (GLuint)pw);
    
    
}
void func_org_mini_gl_GL_glVertexAttribI4iv__I_3II_V(JThreadRuntime *runtime, s32 pindex, JArray *pv, s32 offset_pv) {
    
    __refer ptr_pv = (__refer)(intptr_t) offset_pv;
    if(pv) {
        s32 bytes_pv = data_type_bytes[pv->prop.arr_type] * offset_pv;
        ptr_pv = &pv->prop.as_s8_arr[bytes_pv];
    }

    glVertexAttribI4iv((GLuint)pindex, (const GLint*)(ptr_pv));
    
    
}
void func_org_mini_gl_GL_glVertexAttribI4uiv__I_3II_V(JThreadRuntime *runtime, s32 pindex, JArray *pv, s32 offset_pv) {
    
    __refer ptr_pv = (__refer)(intptr_t) offset_pv;
    if(pv) {
        s32 bytes_pv = data_type_bytes[pv->prop.arr_type] * offset_pv;
        ptr_pv = &pv->prop.as_s8_arr[bytes_pv];
    }

    glVertexAttribI4uiv((GLuint)pindex, (const GLuint*)(ptr_pv));
    
    
}
void func_org_mini_gl_GL_glGetUniformuiv__II_3II_V(JThreadRuntime *runtime, s32 pprogram, s32 plocation, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetUniformuiv((GLuint)pprogram, (GLint)plocation, (GLuint*)(ptr_pparams));
    
    
}
s32 func_org_mini_gl_GL_glGetFragDataLocation__I_3B_I(JThreadRuntime *runtime, s32 pprogram, JArray *pname) {
    
    s32 offset_pname = 0;    __refer ptr_pname = (__refer)(intptr_t) offset_pname;
    if(pname) {
        s32 bytes_pname = data_type_bytes[pname->prop.arr_type] * offset_pname;
        ptr_pname = &pname->prop.as_s8_arr[bytes_pname];
    }

    GLint _re_val = glGetFragDataLocation((GLuint)pprogram, (const GLchar*)(ptr_pname));
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glUniform1ui__II_V(JThreadRuntime *runtime, s32 plocation, s32 pv0) {
    

    glUniform1ui((GLint)plocation, (GLuint)pv0);
    
    
}
void func_org_mini_gl_GL_glUniform2ui__III_V(JThreadRuntime *runtime, s32 plocation, s32 pv0, s32 pv1) {
    

    glUniform2ui((GLint)plocation, (GLuint)pv0, (GLuint)pv1);
    
    
}
void func_org_mini_gl_GL_glUniform3ui__IIII_V(JThreadRuntime *runtime, s32 plocation, s32 pv0, s32 pv1, s32 pv2) {
    

    glUniform3ui((GLint)plocation, (GLuint)pv0, (GLuint)pv1, (GLuint)pv2);
    
    
}
void func_org_mini_gl_GL_glUniform4ui__IIIII_V(JThreadRuntime *runtime, s32 plocation, s32 pv0, s32 pv1, s32 pv2, s32 pv3) {
    

    glUniform4ui((GLint)plocation, (GLuint)pv0, (GLuint)pv1, (GLuint)pv2, (GLuint)pv3);
    
    
}
void func_org_mini_gl_GL_glUniform1uiv__II_3II_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform1uiv((GLint)plocation, (GLsizei)pcount, (const GLuint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform2uiv__II_3II_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform2uiv((GLint)plocation, (GLsizei)pcount, (const GLuint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform3uiv__II_3II_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform3uiv((GLint)plocation, (GLsizei)pcount, (const GLuint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glUniform4uiv__II_3II_V(JThreadRuntime *runtime, s32 plocation, s32 pcount, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glUniform4uiv((GLint)plocation, (GLsizei)pcount, (const GLuint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glClearBufferiv__II_3II_V(JThreadRuntime *runtime, s32 pbuffer, s32 pdrawbuffer, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glClearBufferiv((GLenum)pbuffer, (GLint)pdrawbuffer, (const GLint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glClearBufferuiv__II_3II_V(JThreadRuntime *runtime, s32 pbuffer, s32 pdrawbuffer, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glClearBufferuiv((GLenum)pbuffer, (GLint)pdrawbuffer, (const GLuint*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glClearBufferfv__II_3FI_V(JThreadRuntime *runtime, s32 pbuffer, s32 pdrawbuffer, JArray *pvalue, s32 offset_pvalue) {
    
    __refer ptr_pvalue = (__refer)(intptr_t) offset_pvalue;
    if(pvalue) {
        s32 bytes_pvalue = data_type_bytes[pvalue->prop.arr_type] * offset_pvalue;
        ptr_pvalue = &pvalue->prop.as_s8_arr[bytes_pvalue];
    }

    glClearBufferfv((GLenum)pbuffer, (GLint)pdrawbuffer, (const GLfloat*)(ptr_pvalue));
    
    
}
void func_org_mini_gl_GL_glClearBufferfi__IIFI_V(JThreadRuntime *runtime, s32 pbuffer, s32 pdrawbuffer, f32 pdepth, s32 pstencil) {
    

    glClearBufferfi((GLenum)pbuffer, (GLint)pdrawbuffer, (GLfloat)pdepth, (GLint)pstencil);
    
    
}
JArray * func_org_mini_gl_GL_glGetStringi__II__3B(JThreadRuntime *runtime, s32 pname, s32 pindex) {
    

    const GLubyte* _re_val = glGetStringi((GLenum)pname, (GLuint)pindex);
    c8* _ptr_re_val = (c8*)_re_val;
    if (_ptr_re_val) {
        s32 bytes = strlen(_ptr_re_val);
        s32 j_t_bytes = sizeof(c8) * bytes;
        JArray *_arr = multi_array_create_by_typename(runtime, &j_t_bytes, 1, "[B");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , j_t_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}
void func_org_mini_gl_GL_glCopyBufferSubData__IIJJJ_V(JThreadRuntime *runtime, s32 preadTarget, s32 pwriteTarget, s64 preadOffset, s64 pwriteOffset, s64 psize) {
    

    glCopyBufferSubData((GLenum)preadTarget, (GLenum)pwriteTarget, (GLintptr)preadOffset, (GLintptr)pwriteOffset, (GLsizeiptr)psize);
    
    
}
void func_org_mini_gl_GL_glGetUniformIndices__II_3_3B_3II_V(JThreadRuntime *runtime, s32 pprogram, s32 puniformCount, JArray *puniformNames, JArray *puniformIndices, s32 offset_puniformIndices) {
    
    __refer ptr_puniformNames[puniformNames->prop.arr_length];
    s32 i;for(i=0;i<puniformNames->prop.arr_length;i++){
        JArray *arr_puniformNames = (JArray *)puniformNames->prop.as_obj_arr[i];
        ptr_puniformNames[i] = arr_puniformNames->prop.as_c8_arr;
    }
    __refer ptr_puniformIndices = (__refer)(intptr_t) offset_puniformIndices;
    if(puniformIndices) {
        s32 bytes_puniformIndices = data_type_bytes[puniformIndices->prop.arr_type] * offset_puniformIndices;
        ptr_puniformIndices = &puniformIndices->prop.as_s8_arr[bytes_puniformIndices];
    }

    glGetUniformIndices((GLuint)pprogram, (GLsizei)puniformCount, (const GLchar*const*)(ptr_puniformNames), (GLuint*)(ptr_puniformIndices));
    
    
}
void func_org_mini_gl_GL_glGetActiveUniformsiv__II_3III_3II_V(JThreadRuntime *runtime, s32 pprogram, s32 puniformCount, JArray *puniformIndices, s32 offset_puniformIndices, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_puniformIndices = (__refer)(intptr_t) offset_puniformIndices;
    if(puniformIndices) {
        s32 bytes_puniformIndices = data_type_bytes[puniformIndices->prop.arr_type] * offset_puniformIndices;
        ptr_puniformIndices = &puniformIndices->prop.as_s8_arr[bytes_puniformIndices];
    }
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetActiveUniformsiv((GLuint)pprogram, (GLsizei)puniformCount, (const GLuint*)(ptr_puniformIndices), (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
s32 func_org_mini_gl_GL_glGetUniformBlockIndex__I_3B_I(JThreadRuntime *runtime, s32 pprogram, JArray *puniformBlockName) {
    
    s32 offset_puniformBlockName = 0;    __refer ptr_puniformBlockName = (__refer)(intptr_t) offset_puniformBlockName;
    if(puniformBlockName) {
        s32 bytes_puniformBlockName = data_type_bytes[puniformBlockName->prop.arr_type] * offset_puniformBlockName;
        ptr_puniformBlockName = &puniformBlockName->prop.as_s8_arr[bytes_puniformBlockName];
    }

    GLuint _re_val = glGetUniformBlockIndex((GLuint)pprogram, (const GLchar*)(ptr_puniformBlockName));
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glGetActiveUniformBlockiv__III_3II_V(JThreadRuntime *runtime, s32 pprogram, s32 puniformBlockIndex, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetActiveUniformBlockiv((GLuint)pprogram, (GLuint)puniformBlockIndex, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetActiveUniformBlockName__III_3II_3B_V(JThreadRuntime *runtime, s32 pprogram, s32 puniformBlockIndex, s32 pbufSize, JArray *plength, s32 offset_plength, JArray *puniformBlockName) {
    
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }
    s32 offset_puniformBlockName = 0;    __refer ptr_puniformBlockName = (__refer)(intptr_t) offset_puniformBlockName;
    if(puniformBlockName) {
        s32 bytes_puniformBlockName = data_type_bytes[puniformBlockName->prop.arr_type] * offset_puniformBlockName;
        ptr_puniformBlockName = &puniformBlockName->prop.as_s8_arr[bytes_puniformBlockName];
    }

    glGetActiveUniformBlockName((GLuint)pprogram, (GLuint)puniformBlockIndex, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLchar*)(ptr_puniformBlockName));
    
    
}
void func_org_mini_gl_GL_glUniformBlockBinding__III_V(JThreadRuntime *runtime, s32 pprogram, s32 puniformBlockIndex, s32 puniformBlockBinding) {
    

    glUniformBlockBinding((GLuint)pprogram, (GLuint)puniformBlockIndex, (GLuint)puniformBlockBinding);
    
    
}
void func_org_mini_gl_GL_glDrawArraysInstanced__IIII_V(JThreadRuntime *runtime, s32 pmode, s32 pfirst, s32 pcount, s32 pinstancecount) {
    

    glDrawArraysInstanced((GLenum)pmode, (GLint)pfirst, (GLsizei)pcount, (GLsizei)pinstancecount);
    
    
}
void func_org_mini_gl_GL_glDrawElementsInstanced__IIILjava_lang_Object_2II_V(JThreadRuntime *runtime, s32 pmode, s32 pcount, s32 ptype, struct java_lang_Object *pindices, s32 offset_pindices, s32 pinstancecount) {
    
    __refer ptr_pindices = (__refer)(intptr_t) offset_pindices;
    if(pindices) {
        s32 bytes_pindices = data_type_bytes[pindices->prop.arr_type] * offset_pindices;
        ptr_pindices = &pindices->prop.as_s8_arr[bytes_pindices];
    }

    glDrawElementsInstanced((GLenum)pmode, (GLsizei)pcount, (GLenum)ptype, (const void*)(ptr_pindices), (GLsizei)pinstancecount);
    
    
}
s64 func_org_mini_gl_GL_glFenceSync__II_J(JThreadRuntime *runtime, s32 pcondition, s32 pflags) {
    

    GLsync _re_val = glFenceSync((GLenum)pcondition, (GLbitfield)pflags);
    return *((s64*)&_re_val);
    
}
s32 func_org_mini_gl_GL_glIsSync__J_I(JThreadRuntime *runtime, s64 psync) {
    

    GLboolean _re_val = glIsSync((GLsync)psync);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glDeleteSync__J_V(JThreadRuntime *runtime, s64 psync) {
    

    glDeleteSync((GLsync)psync);
    
    
}
s32 func_org_mini_gl_GL_glClientWaitSync__JIJ_I(JThreadRuntime *runtime, s64 psync, s32 pflags, s64 ptimeout) {
    

    GLenum _re_val = glClientWaitSync((GLsync)psync, (GLbitfield)pflags, (GLuint64)ptimeout);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glWaitSync__JIJ_V(JThreadRuntime *runtime, s64 psync, s32 pflags, s64 ptimeout) {
    

    glWaitSync((GLsync)psync, (GLbitfield)pflags, (GLuint64)ptimeout);
    
    
}
void func_org_mini_gl_GL_glGetInteger64v__I_3JI_V(JThreadRuntime *runtime, s32 ppname, JArray *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glGetInteger64v((GLenum)ppname, (GLint64*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glGetSynciv__JII_3II_3II_V(JThreadRuntime *runtime, s64 psync, s32 ppname, s32 pcount, JArray *plength, s32 offset_plength, JArray *pvalues, s32 offset_pvalues) {
    
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }
    __refer ptr_pvalues = (__refer)(intptr_t) offset_pvalues;
    if(pvalues) {
        s32 bytes_pvalues = data_type_bytes[pvalues->prop.arr_type] * offset_pvalues;
        ptr_pvalues = &pvalues->prop.as_s8_arr[bytes_pvalues];
    }

    glGetSynciv((GLsync)psync, (GLenum)ppname, (GLsizei)pcount, (GLsizei*)(ptr_plength), (GLint*)(ptr_pvalues));
    
    
}
void func_org_mini_gl_GL_glGetInteger64i_1v__II_3JI_V(JThreadRuntime *runtime, s32 ptarget, s32 pindex, JArray *pdata, s32 offset_pdata) {
    
    __refer ptr_pdata = (__refer)(intptr_t) offset_pdata;
    if(pdata) {
        s32 bytes_pdata = data_type_bytes[pdata->prop.arr_type] * offset_pdata;
        ptr_pdata = &pdata->prop.as_s8_arr[bytes_pdata];
    }

    glGetInteger64i_v((GLenum)ptarget, (GLuint)pindex, (GLint64*)(ptr_pdata));
    
    
}
void func_org_mini_gl_GL_glGetBufferParameteri64v__II_3JI_V(JThreadRuntime *runtime, s32 ptarget, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetBufferParameteri64v((GLenum)ptarget, (GLenum)ppname, (GLint64*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGenSamplers__I_3II_V(JThreadRuntime *runtime, s32 pcount, JArray *psamplers, s32 offset_psamplers) {
    
    __refer ptr_psamplers = (__refer)(intptr_t) offset_psamplers;
    if(psamplers) {
        s32 bytes_psamplers = data_type_bytes[psamplers->prop.arr_type] * offset_psamplers;
        ptr_psamplers = &psamplers->prop.as_s8_arr[bytes_psamplers];
    }

    glGenSamplers((GLsizei)pcount, (GLuint*)(ptr_psamplers));
    
    
}
void func_org_mini_gl_GL_glDeleteSamplers__I_3II_V(JThreadRuntime *runtime, s32 pcount, JArray *psamplers, s32 offset_psamplers) {
    
    __refer ptr_psamplers = (__refer)(intptr_t) offset_psamplers;
    if(psamplers) {
        s32 bytes_psamplers = data_type_bytes[psamplers->prop.arr_type] * offset_psamplers;
        ptr_psamplers = &psamplers->prop.as_s8_arr[bytes_psamplers];
    }

    glDeleteSamplers((GLsizei)pcount, (const GLuint*)(ptr_psamplers));
    
    
}
s32 func_org_mini_gl_GL_glIsSampler__I_I(JThreadRuntime *runtime, s32 psampler) {
    

    GLboolean _re_val = glIsSampler((GLuint)psampler);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glBindSampler__II_V(JThreadRuntime *runtime, s32 punit, s32 psampler) {
    

    glBindSampler((GLuint)punit, (GLuint)psampler);
    
    
}
void func_org_mini_gl_GL_glSamplerParameteri__III_V(JThreadRuntime *runtime, s32 psampler, s32 ppname, s32 pparam) {
    

    glSamplerParameteri((GLuint)psampler, (GLenum)ppname, (GLint)pparam);
    
    
}
void func_org_mini_gl_GL_glSamplerParameteriv__II_3II_V(JThreadRuntime *runtime, s32 psampler, s32 ppname, JArray *pparam, s32 offset_pparam) {
    
    __refer ptr_pparam = (__refer)(intptr_t) offset_pparam;
    if(pparam) {
        s32 bytes_pparam = data_type_bytes[pparam->prop.arr_type] * offset_pparam;
        ptr_pparam = &pparam->prop.as_s8_arr[bytes_pparam];
    }

    glSamplerParameteriv((GLuint)psampler, (GLenum)ppname, (const GLint*)(ptr_pparam));
    
    
}
void func_org_mini_gl_GL_glSamplerParameterf__IIF_V(JThreadRuntime *runtime, s32 psampler, s32 ppname, f32 pparam) {
    

    glSamplerParameterf((GLuint)psampler, (GLenum)ppname, (GLfloat)pparam);
    
    
}
void func_org_mini_gl_GL_glSamplerParameterfv__II_3FI_V(JThreadRuntime *runtime, s32 psampler, s32 ppname, JArray *pparam, s32 offset_pparam) {
    
    __refer ptr_pparam = (__refer)(intptr_t) offset_pparam;
    if(pparam) {
        s32 bytes_pparam = data_type_bytes[pparam->prop.arr_type] * offset_pparam;
        ptr_pparam = &pparam->prop.as_s8_arr[bytes_pparam];
    }

    glSamplerParameterfv((GLuint)psampler, (GLenum)ppname, (const GLfloat*)(ptr_pparam));
    
    
}
void func_org_mini_gl_GL_glGetSamplerParameteriv__II_3II_V(JThreadRuntime *runtime, s32 psampler, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetSamplerParameteriv((GLuint)psampler, (GLenum)ppname, (GLint*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glGetSamplerParameterfv__II_3FI_V(JThreadRuntime *runtime, s32 psampler, s32 ppname, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetSamplerParameterfv((GLuint)psampler, (GLenum)ppname, (GLfloat*)(ptr_pparams));
    
    
}
void func_org_mini_gl_GL_glVertexAttribDivisor__II_V(JThreadRuntime *runtime, s32 pindex, s32 pdivisor) {
    

    glVertexAttribDivisor((GLuint)pindex, (GLuint)pdivisor);
    
    
}
void func_org_mini_gl_GL_glBindTransformFeedback__II_V(JThreadRuntime *runtime, s32 ptarget, s32 pid) {
    

    glBindTransformFeedback((GLenum)ptarget, (GLuint)pid);
    
    
}
void func_org_mini_gl_GL_glDeleteTransformFeedbacks__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *pids, s32 offset_pids) {
    
    __refer ptr_pids = (__refer)(intptr_t) offset_pids;
    if(pids) {
        s32 bytes_pids = data_type_bytes[pids->prop.arr_type] * offset_pids;
        ptr_pids = &pids->prop.as_s8_arr[bytes_pids];
    }

    glDeleteTransformFeedbacks((GLsizei)pn, (const GLuint*)(ptr_pids));
    
    
}
void func_org_mini_gl_GL_glGenTransformFeedbacks__I_3II_V(JThreadRuntime *runtime, s32 pn, JArray *pids, s32 offset_pids) {
    
    __refer ptr_pids = (__refer)(intptr_t) offset_pids;
    if(pids) {
        s32 bytes_pids = data_type_bytes[pids->prop.arr_type] * offset_pids;
        ptr_pids = &pids->prop.as_s8_arr[bytes_pids];
    }

    glGenTransformFeedbacks((GLsizei)pn, (GLuint*)(ptr_pids));
    
    
}
s32 func_org_mini_gl_GL_glIsTransformFeedback__I_I(JThreadRuntime *runtime, s32 pid) {
    

    GLboolean _re_val = glIsTransformFeedback((GLuint)pid);
    return *((s32*)&_re_val);
    
}
void func_org_mini_gl_GL_glPauseTransformFeedback___V(JThreadRuntime *runtime) {
    

    glPauseTransformFeedback();
    
    
}
void func_org_mini_gl_GL_glResumeTransformFeedback___V(JThreadRuntime *runtime) {
    

    glResumeTransformFeedback();
    
    
}
void func_org_mini_gl_GL_glGetProgramBinary__II_3II_3IILjava_lang_Object_2I_V(JThreadRuntime *runtime, s32 pprogram, s32 pbufSize, JArray *plength, s32 offset_plength, JArray *pbinaryFormat, s32 offset_pbinaryFormat, struct java_lang_Object *pbinary, s32 offset_pbinary) {
    
    __refer ptr_plength = (__refer)(intptr_t) offset_plength;
    if(plength) {
        s32 bytes_plength = data_type_bytes[plength->prop.arr_type] * offset_plength;
        ptr_plength = &plength->prop.as_s8_arr[bytes_plength];
    }
    __refer ptr_pbinaryFormat = (__refer)(intptr_t) offset_pbinaryFormat;
    if(pbinaryFormat) {
        s32 bytes_pbinaryFormat = data_type_bytes[pbinaryFormat->prop.arr_type] * offset_pbinaryFormat;
        ptr_pbinaryFormat = &pbinaryFormat->prop.as_s8_arr[bytes_pbinaryFormat];
    }
    __refer ptr_pbinary = (__refer)(intptr_t) offset_pbinary;
    if(pbinary) {
        s32 bytes_pbinary = data_type_bytes[pbinary->prop.arr_type] * offset_pbinary;
        ptr_pbinary = &pbinary->prop.as_s8_arr[bytes_pbinary];
    }

    glGetProgramBinary((GLuint)pprogram, (GLsizei)pbufSize, (GLsizei*)(ptr_plength), (GLenum*)(ptr_pbinaryFormat), (void*)(ptr_pbinary));
    
    
}
void func_org_mini_gl_GL_glProgramBinary__IILjava_lang_Object_2II_V(JThreadRuntime *runtime, s32 pprogram, s32 pbinaryFormat, struct java_lang_Object *pbinary, s32 offset_pbinary, s32 plength) {
    
    __refer ptr_pbinary = (__refer)(intptr_t) offset_pbinary;
    if(pbinary) {
        s32 bytes_pbinary = data_type_bytes[pbinary->prop.arr_type] * offset_pbinary;
        ptr_pbinary = &pbinary->prop.as_s8_arr[bytes_pbinary];
    }

    glProgramBinary((GLuint)pprogram, (GLenum)pbinaryFormat, (const void*)(ptr_pbinary), (GLsizei)plength);
    
    
}
void func_org_mini_gl_GL_glProgramParameteri__III_V(JThreadRuntime *runtime, s32 pprogram, s32 ppname, s32 pvalue) {
    

    glProgramParameteri((GLuint)pprogram, (GLenum)ppname, (GLint)pvalue);
    
    
}
void func_org_mini_gl_GL_glInvalidateFramebuffer__II_3II_V(JThreadRuntime *runtime, s32 ptarget, s32 pnumAttachments, JArray *pattachments, s32 offset_pattachments) {
    
    __refer ptr_pattachments = (__refer)(intptr_t) offset_pattachments;
    if(pattachments) {
        s32 bytes_pattachments = data_type_bytes[pattachments->prop.arr_type] * offset_pattachments;
        ptr_pattachments = &pattachments->prop.as_s8_arr[bytes_pattachments];
    }

    glInvalidateFramebuffer((GLenum)ptarget, (GLsizei)pnumAttachments, (const GLenum*)(ptr_pattachments));
    
    
}
void func_org_mini_gl_GL_glInvalidateSubFramebuffer__II_3IIIIII_V(JThreadRuntime *runtime, s32 ptarget, s32 pnumAttachments, JArray *pattachments, s32 offset_pattachments, s32 px, s32 py, s32 pwidth, s32 pheight) {
    
    __refer ptr_pattachments = (__refer)(intptr_t) offset_pattachments;
    if(pattachments) {
        s32 bytes_pattachments = data_type_bytes[pattachments->prop.arr_type] * offset_pattachments;
        ptr_pattachments = &pattachments->prop.as_s8_arr[bytes_pattachments];
    }

    glInvalidateSubFramebuffer((GLenum)ptarget, (GLsizei)pnumAttachments, (const GLenum*)(ptr_pattachments), (GLint)px, (GLint)py, (GLsizei)pwidth, (GLsizei)pheight);
    
    
}
void func_org_mini_gl_GL_glTexStorage2D__IIIII_V(JThreadRuntime *runtime, s32 ptarget, s32 plevels, s32 pinternalformat, s32 pwidth, s32 pheight) {
    

    glTexStorage2D((GLenum)ptarget, (GLsizei)plevels, (GLenum)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight);
    
    
}
void func_org_mini_gl_GL_glTexStorage3D__IIIIII_V(JThreadRuntime *runtime, s32 ptarget, s32 plevels, s32 pinternalformat, s32 pwidth, s32 pheight, s32 pdepth) {
    

    glTexStorage3D((GLenum)ptarget, (GLsizei)plevels, (GLenum)pinternalformat, (GLsizei)pwidth, (GLsizei)pheight, (GLsizei)pdepth);
    
    
}
void func_org_mini_gl_GL_glGetInternalformativ__IIII_3II_V(JThreadRuntime *runtime, s32 ptarget, s32 pinternalformat, s32 ppname, s32 pcount, JArray *pparams, s32 offset_pparams) {
    
    __refer ptr_pparams = (__refer)(intptr_t) offset_pparams;
    if(pparams) {
        s32 bytes_pparams = data_type_bytes[pparams->prop.arr_type] * offset_pparams;
        ptr_pparams = &pparams->prop.as_s8_arr[bytes_pparams];
    }

    glGetInternalformativ((GLenum)ptarget, (GLenum)pinternalformat, (GLenum)ppname, (GLsizei)pcount, (GLint*)(ptr_pparams));
    
    
}



