/*this file generated by Nanovg_java_2_c_for_cc.java ,dont modify it manual.*/
#include <stdio.h>
#include <string.h>

#include <glad.h>

//#define STB_TRUETYPE_IMPLEMENTATION
#include <stb_truetype.h>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb_image_write.h>

//#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>


#include <nanovg.h>
#include <nanovg_jni_assist.h>
#define NANOVG_GLES3_IMPLEMENTATION
#include <nanovg_gl.h>




#include "jvm.h"
#include "media.h"
#include "jni_stb_assist.h"
#include "metadata.h"



s32 func_org_mini_nanovg_Nanovg_stbtt_1InitFont__J_3BI_I(JThreadRuntime *runtime, s64 pinfo, JArray *pdata2, s32 pfontstart) {
    
    __refer ptr_pdata2 = pdata2?pdata2->prop.as_s8_arr:NULL;

    int _re_val = stbtt_InitFont((stbtt_fontinfo*/*ptr*/)pinfo, (const unsigned char*)(ptr_pdata2), (int)pfontstart);
    return *((s32*)&_re_val);
    
}

f32 func_org_mini_nanovg_Nanovg_stbtt_1ScaleForPixelHeight__JF_F(JThreadRuntime *runtime, s64 pinfo, f32 ppixels) {
    

    return (f32)stbtt_ScaleForPixelHeight((const stbtt_fontinfo*/*ptr*/)pinfo, (float)ppixels);
    
    
}

void func_org_mini_nanovg_Nanovg_stbtt_1GetFontVMetrics__J_3I_3I_3I_V(JThreadRuntime *runtime, s64 pinfo, JArray *pascent, JArray *pdescent, JArray *plineGap) {
    
    __refer ptr_pascent = pascent?pascent->prop.as_s8_arr:NULL;
    __refer ptr_pdescent = pdescent?pdescent->prop.as_s8_arr:NULL;
    __refer ptr_plineGap = plineGap?plineGap->prop.as_s8_arr:NULL;

    stbtt_GetFontVMetrics((const stbtt_fontinfo*/*ptr*/)pinfo, (int*)(ptr_pascent), (int*)(ptr_pdescent), (int*)(ptr_plineGap));
    
    
}

void func_org_mini_nanovg_Nanovg_stbtt_1GetCodepointBitmapBox__JIFF_3I_3I_3I_3I_V(JThreadRuntime *runtime, s64 pfont, s32 pcodepoint, f32 pscale_x, f32 pscale_y, JArray *pix0, JArray *piy0, JArray *pix1, JArray *piy1) {
    
    __refer ptr_pix0 = pix0?pix0->prop.as_s8_arr:NULL;
    __refer ptr_piy0 = piy0?piy0->prop.as_s8_arr:NULL;
    __refer ptr_pix1 = pix1?pix1->prop.as_s8_arr:NULL;
    __refer ptr_piy1 = piy1?piy1->prop.as_s8_arr:NULL;

    stbtt_GetCodepointBitmapBox((const stbtt_fontinfo*/*ptr*/)pfont, (int)pcodepoint, (float)pscale_x, (float)pscale_y, (int*)(ptr_pix0), (int*)(ptr_piy0), (int*)(ptr_pix1), (int*)(ptr_piy1));
    
    
}

void func_org_mini_nanovg_Nanovg_stbtt_1MakeCodepointBitmapOffset__J_3BIIIIFFI_V(JThreadRuntime *runtime, s64 pinfo, JArray *poutput, s32 poutput_offset, s32 pout_w, s32 pout_h, s32 pout_stride, f32 pscale_x, f32 pscale_y, s32 pcodepoint) {
    
    __refer ptr_poutput = poutput?poutput->prop.as_s8_arr:NULL;

    stbtt_MakeCodepointBitmapOffset((const stbtt_fontinfo*/*ptr*/)pinfo, (unsigned char*)(ptr_poutput), (int)poutput_offset, (int)pout_w, (int)pout_h, (int)pout_stride, (float)pscale_x, (float)pscale_y, (int)pcodepoint);
    
    
}

void func_org_mini_nanovg_Nanovg_stbtt_1GetCodepointHMetrics__JI_3I_3I_V(JThreadRuntime *runtime, s64 pinfo, s32 pcodepoint, JArray *padvanceWidth, JArray *pleftSideBearing) {
    
    __refer ptr_padvanceWidth = padvanceWidth?padvanceWidth->prop.as_s8_arr:NULL;
    __refer ptr_pleftSideBearing = pleftSideBearing?pleftSideBearing->prop.as_s8_arr:NULL;

    stbtt_GetCodepointHMetrics((const stbtt_fontinfo*/*ptr*/)pinfo, (int)pcodepoint, (int*)(ptr_padvanceWidth), (int*)(ptr_pleftSideBearing));
    
    
}

s32 func_org_mini_nanovg_Nanovg_stbtt_1GetCodepointKernAdvance__JII_I(JThreadRuntime *runtime, s64 pinfo, s32 pch1, s32 pch2) {
    

    int _re_val = stbtt_GetCodepointKernAdvance((const stbtt_fontinfo*/*ptr*/)pinfo, (int)pch1, (int)pch2);
    return *((s32*)&_re_val);
    
}

JArray * func_org_mini_nanovg_Nanovg_stbtt_1MakeFontInfo____3B(JThreadRuntime *runtime) {
    

    struct stbtt_fontinfo/*none_ptr*/ _re_val = stbtt_MakeFontInfo();
    c8* _ptr_re_val = (c8*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(c8);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[B");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

s8 func_org_mini_nanovg_Nanovg_access_1mem__J_B(JThreadRuntime *runtime, s64 pptr) {
    

    return (s8)access_mem((stbi_uc*/*ptr*/)pptr);
    
    
}

s32 func_org_mini_nanovg_Nanovg_stbi_1write_1png___3BIIIJI_I(JThreadRuntime *runtime, JArray *pfilename, s32 pw, s32 ph, s32 pcomp, s64 pdata, s32 pstride_in_bytes) {
    
    __refer ptr_pfilename = pfilename?pfilename->prop.as_s8_arr:NULL;

    int _re_val = stbi_write_png((char const*)(ptr_pfilename), (int)pw, (int)ph, (int)pcomp, (const void*/*ptr*/)pdata, (int)pstride_in_bytes);
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_stbi_1write_1bmp___3BIIIJ_I(JThreadRuntime *runtime, JArray *pfilename, s32 pw, s32 ph, s32 pcomp, s64 pdata) {
    
    __refer ptr_pfilename = pfilename?pfilename->prop.as_s8_arr:NULL;

    int _re_val = stbi_write_bmp((char const*)(ptr_pfilename), (int)pw, (int)ph, (int)pcomp, (const void*/*ptr*/)pdata);
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_stbi_1write_1tga___3BIIIJ_I(JThreadRuntime *runtime, JArray *pfilename, s32 pw, s32 ph, s32 pcomp, s64 pdata) {
    
    __refer ptr_pfilename = pfilename?pfilename->prop.as_s8_arr:NULL;

    int _re_val = stbi_write_tga((char const*)(ptr_pfilename), (int)pw, (int)ph, (int)pcomp, (const void*/*ptr*/)pdata);
    return *((s32*)&_re_val);
    
}

s64 func_org_mini_nanovg_Nanovg_stbi_1load___3B_3I_3I_3II_J(JThreadRuntime *runtime, JArray *pfilename, JArray *px, JArray *py, JArray *pcomp, s32 preq_comp) {
    
    __refer ptr_pfilename = pfilename?pfilename->prop.as_s8_arr:NULL;
    __refer ptr_px = px?px->prop.as_s8_arr:NULL;
    __refer ptr_py = py?py->prop.as_s8_arr:NULL;
    __refer ptr_pcomp = pcomp?pcomp->prop.as_s8_arr:NULL;

    stbi_uc*/*ptr*/ _re_val = stbi_load((char const*)(ptr_pfilename), (int*)(ptr_px), (int*)(ptr_py), (int*)(ptr_pcomp), (int)preq_comp);
    return *((s64*)&_re_val);
    
}

s64 func_org_mini_nanovg_Nanovg_stbi_1load_1from_1memory__JI_3I_3I_3II_J(JThreadRuntime *runtime, s64 pbuffer, s32 plen, JArray *px, JArray *py, JArray *pcomp, s32 preq_comp) {
    
    __refer ptr_px = px?px->prop.as_s8_arr:NULL;
    __refer ptr_py = py?py->prop.as_s8_arr:NULL;
    __refer ptr_pcomp = pcomp?pcomp->prop.as_s8_arr:NULL;

    stbi_uc*/*ptr*/ _re_val = stbi_load_from_memory((stbi_uc const*/*ptr*/)pbuffer, (int)plen, (int*)(ptr_px), (int*)(ptr_py), (int*)(ptr_pcomp), (int)preq_comp);
    return *((s64*)&_re_val);
    
}

void func_org_mini_nanovg_Nanovg_stbi_1image_1free__J_V(JThreadRuntime *runtime, s64 pretval_from_stbi_load) {
    

    stbi_image_free((void*/*ptr*/)pretval_from_stbi_load);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgBeginFrame__JIIF_V(JThreadRuntime *runtime, s64 pctx, s32 pwindowWidth, s32 pwindowHeight, f32 pdevicePixelRatio) {
    

    nvgBeginFrame((NVGcontext*/*ptr*/)pctx, (int)pwindowWidth, (int)pwindowHeight, (float)pdevicePixelRatio);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgCancelFrame__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgCancelFrame((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgEndFrame__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgEndFrame((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgGlobalCompositeOperation__JI_V(JThreadRuntime *runtime, s64 pctx, s32 pop) {
    

    nvgGlobalCompositeOperation((NVGcontext*/*ptr*/)pctx, (int)pop);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgGlobalCompositeBlendFunc__JII_V(JThreadRuntime *runtime, s64 pctx, s32 psfactor, s32 pdfactor) {
    

    nvgGlobalCompositeBlendFunc((NVGcontext*/*ptr*/)pctx, (int)psfactor, (int)pdfactor);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgGlobalCompositeBlendFuncSeparate__JIIII_V(JThreadRuntime *runtime, s64 pctx, s32 psrcRGB, s32 pdstRGB, s32 psrcAlpha, s32 pdstAlpha) {
    

    nvgGlobalCompositeBlendFuncSeparate((NVGcontext*/*ptr*/)pctx, (int)psrcRGB, (int)pdstRGB, (int)psrcAlpha, (int)pdstAlpha);
    
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgRGB__BBB__3F(JThreadRuntime *runtime, s8 pr, s8 pg, s8 pb) {
    

    NVGcolor/*none_ptr*/ _re_val = nvgRGB((unsigned char)pr, (unsigned char)pg, (unsigned char)pb);
    f32* _ptr_re_val = (f32*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(f32);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[F");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgRGBf__FFF__3F(JThreadRuntime *runtime, f32 pr, f32 pg, f32 pb) {
    

    NVGcolor/*none_ptr*/ _re_val = nvgRGBf((float)pr, (float)pg, (float)pb);
    f32* _ptr_re_val = (f32*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(f32);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[F");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgRGBA__BBBB__3F(JThreadRuntime *runtime, s8 pr, s8 pg, s8 pb, s8 pa) {
    

    NVGcolor/*none_ptr*/ _re_val = nvgRGBA((unsigned char)pr, (unsigned char)pg, (unsigned char)pb, (unsigned char)pa);
    f32* _ptr_re_val = (f32*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(f32);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[F");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgRGBAf__FFFF__3F(JThreadRuntime *runtime, f32 pr, f32 pg, f32 pb, f32 pa) {
    

    NVGcolor/*none_ptr*/ _re_val = nvgRGBAf((float)pr, (float)pg, (float)pb, (float)pa);
    f32* _ptr_re_val = (f32*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(f32);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[F");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgLerpRGBA___3F_3FF__3F(JThreadRuntime *runtime, JArray *pc0, JArray *pc1, f32 pu) {
    
    __refer ptr_pc0 = pc0?pc0->prop.as_s8_arr:NULL;
    __refer ptr_pc1 = pc1?pc1->prop.as_s8_arr:NULL;

    NVGcolor/*none_ptr*/ _re_val = nvgLerpRGBA(*(NVGcolor/*none_ptr*/*)(ptr_pc0), *(NVGcolor/*none_ptr*/*)(ptr_pc1), (float)pu);
    f32* _ptr_re_val = (f32*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(f32);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[F");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgTransRGBA___3FB__3F(JThreadRuntime *runtime, JArray *pc0, s8 pa) {
    
    __refer ptr_pc0 = pc0?pc0->prop.as_s8_arr:NULL;

    NVGcolor/*none_ptr*/ _re_val = nvgTransRGBA(*(NVGcolor/*none_ptr*/*)(ptr_pc0), (unsigned char)pa);
    f32* _ptr_re_val = (f32*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(f32);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[F");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgTransRGBAf___3FF__3F(JThreadRuntime *runtime, JArray *pc0, f32 pa) {
    
    __refer ptr_pc0 = pc0?pc0->prop.as_s8_arr:NULL;

    NVGcolor/*none_ptr*/ _re_val = nvgTransRGBAf(*(NVGcolor/*none_ptr*/*)(ptr_pc0), (float)pa);
    f32* _ptr_re_val = (f32*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(f32);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[F");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgHSL__FFF__3F(JThreadRuntime *runtime, f32 ph, f32 ps, f32 pl) {
    

    NVGcolor/*none_ptr*/ _re_val = nvgHSL((float)ph, (float)ps, (float)pl);
    f32* _ptr_re_val = (f32*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(f32);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[F");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgHSLA__FFFB__3F(JThreadRuntime *runtime, f32 ph, f32 ps, f32 pl, s8 pa) {
    

    NVGcolor/*none_ptr*/ _re_val = nvgHSLA((float)ph, (float)ps, (float)pl, (unsigned char)pa);
    f32* _ptr_re_val = (f32*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(f32);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[F");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

void func_org_mini_nanovg_Nanovg_nvgSave__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgSave((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgRestore__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgRestore((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgReset__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgReset((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgShapeAntiAlias__JI_V(JThreadRuntime *runtime, s64 pctx, s32 penabled) {
    

    nvgShapeAntiAlias((NVGcontext*/*ptr*/)pctx, (int)penabled);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgStrokeColor__J_3F_V(JThreadRuntime *runtime, s64 pctx, JArray *pcolor) {
    
    __refer ptr_pcolor = pcolor?pcolor->prop.as_s8_arr:NULL;

    nvgStrokeColor((NVGcontext*/*ptr*/)pctx, *(NVGcolor/*none_ptr*/*)(ptr_pcolor));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgStrokePaint__J_3B_V(JThreadRuntime *runtime, s64 pctx, JArray *ppaint) {
    
    __refer ptr_ppaint = ppaint?ppaint->prop.as_s8_arr:NULL;

    nvgStrokePaint((NVGcontext*/*ptr*/)pctx, *(NVGpaint/*none_ptr*/*)(ptr_ppaint));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgFillColor__J_3F_V(JThreadRuntime *runtime, s64 pctx, JArray *pcolor) {
    
    __refer ptr_pcolor = pcolor?pcolor->prop.as_s8_arr:NULL;

    nvgFillColor((NVGcontext*/*ptr*/)pctx, *(NVGcolor/*none_ptr*/*)(ptr_pcolor));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgFillPaint__J_3B_V(JThreadRuntime *runtime, s64 pctx, JArray *ppaint) {
    
    __refer ptr_ppaint = ppaint?ppaint->prop.as_s8_arr:NULL;

    nvgFillPaint((NVGcontext*/*ptr*/)pctx, *(NVGpaint/*none_ptr*/*)(ptr_ppaint));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgMiterLimit__JF_V(JThreadRuntime *runtime, s64 pctx, f32 plimit) {
    

    nvgMiterLimit((NVGcontext*/*ptr*/)pctx, (float)plimit);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgStrokeWidth__JF_V(JThreadRuntime *runtime, s64 pctx, f32 psize) {
    

    nvgStrokeWidth((NVGcontext*/*ptr*/)pctx, (float)psize);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgLineCap__JI_V(JThreadRuntime *runtime, s64 pctx, s32 pcap) {
    

    nvgLineCap((NVGcontext*/*ptr*/)pctx, (int)pcap);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgLineJoin__JI_V(JThreadRuntime *runtime, s64 pctx, s32 pjoin) {
    

    nvgLineJoin((NVGcontext*/*ptr*/)pctx, (int)pjoin);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgGlobalAlpha__JF_V(JThreadRuntime *runtime, s64 pctx, f32 palpha) {
    

    nvgGlobalAlpha((NVGcontext*/*ptr*/)pctx, (float)palpha);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgResetTransform__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgResetTransform((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTransform__JFFFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 pa, f32 pb, f32 pc, f32 pd, f32 pe, f32 pf) {
    

    nvgTransform((NVGcontext*/*ptr*/)pctx, (float)pa, (float)pb, (float)pc, (float)pd, (float)pe, (float)pf);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTranslate__JFF_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py) {
    

    nvgTranslate((NVGcontext*/*ptr*/)pctx, (float)px, (float)py);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgRotate__JF_V(JThreadRuntime *runtime, s64 pctx, f32 pangle) {
    

    nvgRotate((NVGcontext*/*ptr*/)pctx, (float)pangle);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgSkewX__JF_V(JThreadRuntime *runtime, s64 pctx, f32 pangle) {
    

    nvgSkewX((NVGcontext*/*ptr*/)pctx, (float)pangle);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgSkewY__JF_V(JThreadRuntime *runtime, s64 pctx, f32 pangle) {
    

    nvgSkewY((NVGcontext*/*ptr*/)pctx, (float)pangle);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgScale__JFF_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py) {
    

    nvgScale((NVGcontext*/*ptr*/)pctx, (float)px, (float)py);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgCurrentTransform__J_3F_V(JThreadRuntime *runtime, s64 pctx, JArray *pxform) {
    
    __refer ptr_pxform = pxform?pxform->prop.as_s8_arr:NULL;

    nvgCurrentTransform((NVGcontext*/*ptr*/)pctx, (float*)(ptr_pxform));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTransformIdentity___3F_V(JThreadRuntime *runtime, JArray *pdst) {
    
    __refer ptr_pdst = pdst?pdst->prop.as_s8_arr:NULL;

    nvgTransformIdentity((float*)(ptr_pdst));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTransformTranslate___3FFF_V(JThreadRuntime *runtime, JArray *pdst, f32 ptx, f32 pty) {
    
    __refer ptr_pdst = pdst?pdst->prop.as_s8_arr:NULL;

    nvgTransformTranslate((float*)(ptr_pdst), (float)ptx, (float)pty);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTransformScale___3FFF_V(JThreadRuntime *runtime, JArray *pdst, f32 psx, f32 psy) {
    
    __refer ptr_pdst = pdst?pdst->prop.as_s8_arr:NULL;

    nvgTransformScale((float*)(ptr_pdst), (float)psx, (float)psy);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTransformRotate___3FF_V(JThreadRuntime *runtime, JArray *pdst, f32 pa) {
    
    __refer ptr_pdst = pdst?pdst->prop.as_s8_arr:NULL;

    nvgTransformRotate((float*)(ptr_pdst), (float)pa);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTransformSkewX___3FF_V(JThreadRuntime *runtime, JArray *pdst, f32 pa) {
    
    __refer ptr_pdst = pdst?pdst->prop.as_s8_arr:NULL;

    nvgTransformSkewX((float*)(ptr_pdst), (float)pa);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTransformSkewY___3FF_V(JThreadRuntime *runtime, JArray *pdst, f32 pa) {
    
    __refer ptr_pdst = pdst?pdst->prop.as_s8_arr:NULL;

    nvgTransformSkewY((float*)(ptr_pdst), (float)pa);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTransformMultiply___3F_3F_V(JThreadRuntime *runtime, JArray *pdst, JArray *psrc) {
    
    __refer ptr_pdst = pdst?pdst->prop.as_s8_arr:NULL;
    __refer ptr_psrc = psrc?psrc->prop.as_s8_arr:NULL;

    nvgTransformMultiply((float*)(ptr_pdst), (const float*)(ptr_psrc));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTransformPremultiply___3F_3F_V(JThreadRuntime *runtime, JArray *pdst, JArray *psrc) {
    
    __refer ptr_pdst = pdst?pdst->prop.as_s8_arr:NULL;
    __refer ptr_psrc = psrc?psrc->prop.as_s8_arr:NULL;

    nvgTransformPremultiply((float*)(ptr_pdst), (const float*)(ptr_psrc));
    
    
}

s32 func_org_mini_nanovg_Nanovg_nvgTransformInverse___3F_3F_I(JThreadRuntime *runtime, JArray *pdst, JArray *psrc) {
    
    __refer ptr_pdst = pdst?pdst->prop.as_s8_arr:NULL;
    __refer ptr_psrc = psrc?psrc->prop.as_s8_arr:NULL;

    int _re_val = nvgTransformInverse((float*)(ptr_pdst), (const float*)(ptr_psrc));
    return *((s32*)&_re_val);
    
}

void func_org_mini_nanovg_Nanovg_nvgTransformPoint___3F_3F_3FFF_V(JThreadRuntime *runtime, JArray *pdstx, JArray *pdsty, JArray *pxform, f32 psrcx, f32 psrcy) {
    
    __refer ptr_pdstx = pdstx?pdstx->prop.as_s8_arr:NULL;
    __refer ptr_pdsty = pdsty?pdsty->prop.as_s8_arr:NULL;
    __refer ptr_pxform = pxform?pxform->prop.as_s8_arr:NULL;

    nvgTransformPoint((float*)(ptr_pdstx), (float*)(ptr_pdsty), (const float*)(ptr_pxform), (float)psrcx, (float)psrcy);
    
    
}

f32 func_org_mini_nanovg_Nanovg_nvgDegToRad__F_F(JThreadRuntime *runtime, f32 pdeg) {
    

    return (f32)nvgDegToRad((float)pdeg);
    
    
}

f32 func_org_mini_nanovg_Nanovg_nvgRadToDeg__F_F(JThreadRuntime *runtime, f32 prad) {
    

    return (f32)nvgRadToDeg((float)prad);
    
    
}

s32 func_org_mini_nanovg_Nanovg_nvgCreateImage__J_3BI_I(JThreadRuntime *runtime, s64 pctx, JArray *pfilename, s32 pimageFlags) {
    
    __refer ptr_pfilename = pfilename?pfilename->prop.as_s8_arr:NULL;

    int _re_val = nvgCreateImage((NVGcontext*/*ptr*/)pctx, (const char*)(ptr_pfilename), (int)pimageFlags);
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_nvgCreateImageMem__JI_3BI_I(JThreadRuntime *runtime, s64 pctx, s32 pimageFlags, JArray *pdata, s32 pndata) {
    
    __refer ptr_pdata = pdata?pdata->prop.as_s8_arr:NULL;

    int _re_val = nvgCreateImageMem((NVGcontext*/*ptr*/)pctx, (int)pimageFlags, (unsigned char*)(ptr_pdata), (int)pndata);
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_nvgCreateImageRGBA__JIII_3B_I(JThreadRuntime *runtime, s64 pctx, s32 pw, s32 ph, s32 pimageFlags, JArray *pdata) {
    
    __refer ptr_pdata = pdata?pdata->prop.as_s8_arr:NULL;

    int _re_val = nvgCreateImageRGBA((NVGcontext*/*ptr*/)pctx, (int)pw, (int)ph, (int)pimageFlags, (const unsigned char*)(ptr_pdata));
    return *((s32*)&_re_val);
    
}

void func_org_mini_nanovg_Nanovg_nvgUpdateImage__JI_3B_V(JThreadRuntime *runtime, s64 pctx, s32 pimage, JArray *pdata) {
    
    __refer ptr_pdata = pdata?pdata->prop.as_s8_arr:NULL;

    nvgUpdateImage((NVGcontext*/*ptr*/)pctx, (int)pimage, (const unsigned char*)(ptr_pdata));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgImageSize__JI_3I_3I_V(JThreadRuntime *runtime, s64 pctx, s32 pimage, JArray *pw, JArray *ph) {
    
    __refer ptr_pw = pw?pw->prop.as_s8_arr:NULL;
    __refer ptr_ph = ph?ph->prop.as_s8_arr:NULL;

    nvgImageSize((NVGcontext*/*ptr*/)pctx, (int)pimage, (int*)(ptr_pw), (int*)(ptr_ph));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgDeleteImage__JI_V(JThreadRuntime *runtime, s64 pctx, s32 pimage) {
    

    nvgDeleteImage((NVGcontext*/*ptr*/)pctx, (int)pimage);
    
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgLinearGradient__JFFFF_3F_3F__3B(JThreadRuntime *runtime, s64 pctx, f32 psx, f32 psy, f32 pex, f32 pey, JArray *picol, JArray *pocol) {
    
    __refer ptr_picol = picol?picol->prop.as_s8_arr:NULL;
    __refer ptr_pocol = pocol?pocol->prop.as_s8_arr:NULL;

    NVGpaint/*none_ptr*/ _re_val = nvgLinearGradient((NVGcontext*/*ptr*/)pctx, (float)psx, (float)psy, (float)pex, (float)pey, *(NVGcolor/*none_ptr*/*)(ptr_picol), *(NVGcolor/*none_ptr*/*)(ptr_pocol));
    c8* _ptr_re_val = (c8*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(c8);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[B");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgBoxGradient__JFFFFFF_3F_3F__3B(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, f32 pw, f32 ph, f32 pr, f32 pf, JArray *picol, JArray *pocol) {
    
    __refer ptr_picol = picol?picol->prop.as_s8_arr:NULL;
    __refer ptr_pocol = pocol?pocol->prop.as_s8_arr:NULL;

    NVGpaint/*none_ptr*/ _re_val = nvgBoxGradient((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (float)pw, (float)ph, (float)pr, (float)pf, *(NVGcolor/*none_ptr*/*)(ptr_picol), *(NVGcolor/*none_ptr*/*)(ptr_pocol));
    c8* _ptr_re_val = (c8*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(c8);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[B");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgRadialGradient__JFFFF_3F_3F__3B(JThreadRuntime *runtime, s64 pctx, f32 pcx, f32 pcy, f32 pinr, f32 poutr, JArray *picol, JArray *pocol) {
    
    __refer ptr_picol = picol?picol->prop.as_s8_arr:NULL;
    __refer ptr_pocol = pocol?pocol->prop.as_s8_arr:NULL;

    NVGpaint/*none_ptr*/ _re_val = nvgRadialGradient((NVGcontext*/*ptr*/)pctx, (float)pcx, (float)pcy, (float)pinr, (float)poutr, *(NVGcolor/*none_ptr*/*)(ptr_picol), *(NVGcolor/*none_ptr*/*)(ptr_pocol));
    c8* _ptr_re_val = (c8*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(c8);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[B");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

JArray * func_org_mini_nanovg_Nanovg_nvgImagePattern__JFFFFFIF__3B(JThreadRuntime *runtime, s64 pctx, f32 pox, f32 poy, f32 pex, f32 pey, f32 pangle, s32 pimage, f32 palpha) {
    

    NVGpaint/*none_ptr*/ _re_val = nvgImagePattern((NVGcontext*/*ptr*/)pctx, (float)pox, (float)poy, (float)pex, (float)pey, (float)pangle, (int)pimage, (float)palpha);
    c8* _ptr_re_val = (c8*)&_re_val;
    s32 _struct_bytes = sizeof(_re_val);
    if (_ptr_re_val) {
        s32 len = _struct_bytes / sizeof(c8);
        JArray *_arr = multi_array_create_by_typename(runtime, &len, 1, "[B");
        memcpy(_arr->prop.as_c8_arr, _ptr_re_val , _struct_bytes);
        return _arr;
    } else {
        return NULL;
    }
    
}

void func_org_mini_nanovg_Nanovg_nvgScissor__JFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, f32 pw, f32 ph) {
    

    nvgScissor((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (float)pw, (float)ph);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgIntersectScissor__JFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, f32 pw, f32 ph) {
    

    nvgIntersectScissor((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (float)pw, (float)ph);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgResetScissor__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgResetScissor((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgBeginPath__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgBeginPath((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgMoveTo__JFF_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py) {
    

    nvgMoveTo((NVGcontext*/*ptr*/)pctx, (float)px, (float)py);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgLineTo__JFF_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py) {
    

    nvgLineTo((NVGcontext*/*ptr*/)pctx, (float)px, (float)py);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgBezierTo__JFFFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 pc1x, f32 pc1y, f32 pc2x, f32 pc2y, f32 px, f32 py) {
    

    nvgBezierTo((NVGcontext*/*ptr*/)pctx, (float)pc1x, (float)pc1y, (float)pc2x, (float)pc2y, (float)px, (float)py);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgQuadTo__JFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 pcx, f32 pcy, f32 px, f32 py) {
    

    nvgQuadTo((NVGcontext*/*ptr*/)pctx, (float)pcx, (float)pcy, (float)px, (float)py);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgArcTo__JFFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 px1, f32 py1, f32 px2, f32 py2, f32 pradius) {
    

    nvgArcTo((NVGcontext*/*ptr*/)pctx, (float)px1, (float)py1, (float)px2, (float)py2, (float)pradius);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgClosePath__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgClosePath((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgPathWinding__JI_V(JThreadRuntime *runtime, s64 pctx, s32 pdir) {
    

    nvgPathWinding((NVGcontext*/*ptr*/)pctx, (int)pdir);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgArc__JFFFFFI_V(JThreadRuntime *runtime, s64 pctx, f32 pcx, f32 pcy, f32 pr, f32 pa0, f32 pa1, s32 pdir) {
    

    nvgArc((NVGcontext*/*ptr*/)pctx, (float)pcx, (float)pcy, (float)pr, (float)pa0, (float)pa1, (int)pdir);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgRect__JFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, f32 pw, f32 ph) {
    

    nvgRect((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (float)pw, (float)ph);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgRoundedRect__JFFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, f32 pw, f32 ph, f32 pr) {
    

    nvgRoundedRect((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (float)pw, (float)ph, (float)pr);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgRoundedRectVarying__JFFFFFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, f32 pw, f32 ph, f32 pradTopLeft, f32 pradTopRight, f32 pradBottomRight, f32 pradBottomLeft) {
    

    nvgRoundedRectVarying((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (float)pw, (float)ph, (float)pradTopLeft, (float)pradTopRight, (float)pradBottomRight, (float)pradBottomLeft);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgEllipse__JFFFF_V(JThreadRuntime *runtime, s64 pctx, f32 pcx, f32 pcy, f32 prx, f32 pry) {
    

    nvgEllipse((NVGcontext*/*ptr*/)pctx, (float)pcx, (float)pcy, (float)prx, (float)pry);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgCircle__JFFF_V(JThreadRuntime *runtime, s64 pctx, f32 pcx, f32 pcy, f32 pr) {
    

    nvgCircle((NVGcontext*/*ptr*/)pctx, (float)pcx, (float)pcy, (float)pr);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgFill__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgFill((NVGcontext*/*ptr*/)pctx);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgStroke__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgStroke((NVGcontext*/*ptr*/)pctx);
    
    
}

s32 func_org_mini_nanovg_Nanovg_nvgCreateFont__J_3B_3B_I(JThreadRuntime *runtime, s64 pctx, JArray *pname, JArray *pfilename) {
    
    __refer ptr_pname = pname?pname->prop.as_s8_arr:NULL;
    __refer ptr_pfilename = pfilename?pfilename->prop.as_s8_arr:NULL;

    int _re_val = nvgCreateFont((NVGcontext*/*ptr*/)pctx, (const char*)(ptr_pname), (const char*)(ptr_pfilename));
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_nvgCreateFontMem__J_3B_3BII_I(JThreadRuntime *runtime, s64 pctx, JArray *pname, JArray *pdata, s32 pndata, s32 pfreeData) {
    
    __refer ptr_pname = pname?pname->prop.as_s8_arr:NULL;
    __refer ptr_pdata = pdata?pdata->prop.as_s8_arr:NULL;

    int _re_val = nvgCreateFontMem((NVGcontext*/*ptr*/)pctx, (const char*)(ptr_pname), (unsigned char*)(ptr_pdata), (int)pndata, (int)pfreeData);
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_nvgFindFont__J_3B_I(JThreadRuntime *runtime, s64 pctx, JArray *pname) {
    
    __refer ptr_pname = pname?pname->prop.as_s8_arr:NULL;

    int _re_val = nvgFindFont((NVGcontext*/*ptr*/)pctx, (const char*)(ptr_pname));
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_nvgAddFallbackFontId__JII_I(JThreadRuntime *runtime, s64 pctx, s32 pbaseFont, s32 pfallbackFont) {
    

    int _re_val = nvgAddFallbackFontId((NVGcontext*/*ptr*/)pctx, (int)pbaseFont, (int)pfallbackFont);
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_nvgAddFallbackFont__J_3B_3B_I(JThreadRuntime *runtime, s64 pctx, JArray *pbaseFont, JArray *pfallbackFont) {
    
    __refer ptr_pbaseFont = pbaseFont?pbaseFont->prop.as_s8_arr:NULL;
    __refer ptr_pfallbackFont = pfallbackFont?pfallbackFont->prop.as_s8_arr:NULL;

    int _re_val = nvgAddFallbackFont((NVGcontext*/*ptr*/)pctx, (const char*)(ptr_pbaseFont), (const char*)(ptr_pfallbackFont));
    return *((s32*)&_re_val);
    
}

void func_org_mini_nanovg_Nanovg_nvgFontSize__JF_V(JThreadRuntime *runtime, s64 pctx, f32 psize) {
    

    nvgFontSize((NVGcontext*/*ptr*/)pctx, (float)psize);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgFontBlur__JF_V(JThreadRuntime *runtime, s64 pctx, f32 pblur) {
    

    nvgFontBlur((NVGcontext*/*ptr*/)pctx, (float)pblur);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTextLetterSpacing__JF_V(JThreadRuntime *runtime, s64 pctx, f32 pspacing) {
    

    nvgTextLetterSpacing((NVGcontext*/*ptr*/)pctx, (float)pspacing);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTextLineHeight__JF_V(JThreadRuntime *runtime, s64 pctx, f32 plineHeight) {
    

    nvgTextLineHeight((NVGcontext*/*ptr*/)pctx, (float)plineHeight);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTextAlign__JI_V(JThreadRuntime *runtime, s64 pctx, s32 palign) {
    

    nvgTextAlign((NVGcontext*/*ptr*/)pctx, (int)palign);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgFontFaceId__JI_V(JThreadRuntime *runtime, s64 pctx, s32 pfont) {
    

    nvgFontFaceId((NVGcontext*/*ptr*/)pctx, (int)pfont);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgFontFace__J_3B_V(JThreadRuntime *runtime, s64 pctx, JArray *pfont) {
    
    __refer ptr_pfont = pfont?pfont->prop.as_s8_arr:NULL;

    nvgFontFace((NVGcontext*/*ptr*/)pctx, (const char*)(ptr_pfont));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTextMetrics__J_3F_3F_3F_V(JThreadRuntime *runtime, s64 pctx, JArray *pascender, JArray *pdescender, JArray *plineh) {
    
    __refer ptr_pascender = pascender?pascender->prop.as_s8_arr:NULL;
    __refer ptr_pdescender = pdescender?pdescender->prop.as_s8_arr:NULL;
    __refer ptr_plineh = plineh?plineh->prop.as_s8_arr:NULL;

    nvgTextMetrics((NVGcontext*/*ptr*/)pctx, (float*)(ptr_pascender), (float*)(ptr_pdescender), (float*)(ptr_plineh));
    
    
}

s64 func_org_mini_nanovg_Nanovg_nvgCreateGLES3__I_J(JThreadRuntime *runtime, s32 pflags) {
    

    NVGcontext*/*ptr*/ _re_val = nvgCreateGLES3((int)pflags);
    return *((s64*)&_re_val);
    
}

void func_org_mini_nanovg_Nanovg_nvgDeleteGLES3__J_V(JThreadRuntime *runtime, s64 pctx) {
    

    nvgDeleteGLES3((NVGcontext*/*ptr*/)pctx);
    
    
}

s32 func_org_mini_nanovg_Nanovg_nvglCreateImageFromHandleGLES3__JIIII_I(JThreadRuntime *runtime, s64 pctx, s32 ptextureId, s32 pw, s32 ph, s32 pflags) {
    

    int _re_val = nvglCreateImageFromHandleGLES3((NVGcontext*/*ptr*/)pctx, (GLuint)ptextureId, (int)pw, (int)ph, (int)pflags);
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_nvglImageHandleGLES3__JI_I(JThreadRuntime *runtime, s64 pctx, s32 pimage) {
    

    GLuint _re_val = nvglImageHandleGLES3((NVGcontext*/*ptr*/)pctx, (int)pimage);
    return *((s32*)&_re_val);
    
}

s64 func_org_mini_nanovg_Nanovg_nvgCreateNVGtextRow__I_J(JThreadRuntime *runtime, s32 pcount) {
    

    struct NVGtextRow*/*ptr*/ _re_val = nvgCreateNVGtextRow((int)pcount);
    return *((s64*)&_re_val);
    
}

void func_org_mini_nanovg_Nanovg_nvgDeleteNVGtextRow__J_V(JThreadRuntime *runtime, s64 pval) {
    

    nvgDeleteNVGtextRow((struct NVGtextRow*/*ptr*/)pval);
    
    
}

f32 func_org_mini_nanovg_Nanovg_nvgNVGtextRow_1width__JI_F(JThreadRuntime *runtime, s64 pptr, s32 pindex) {
    

    return (f32)nvgNVGtextRow_width((struct NVGtextRow*/*ptr*/)pptr, (int)pindex);
    
    
}

s64 func_org_mini_nanovg_Nanovg_nvgNVGtextRow_1start__JI_J(JThreadRuntime *runtime, s64 pptr, s32 pindex) {
    

    void*/*ptr*/ _re_val = nvgNVGtextRow_start((struct NVGtextRow*/*ptr*/)pptr, (int)pindex);
    return *((s64*)&_re_val);
    
}

s64 func_org_mini_nanovg_Nanovg_nvgNVGtextRow_1end__JI_J(JThreadRuntime *runtime, s64 pptr, s32 pindex) {
    

    void*/*ptr*/ _re_val = nvgNVGtextRow_end((struct NVGtextRow*/*ptr*/)pptr, (int)pindex);
    return *((s64*)&_re_val);
    
}

s64 func_org_mini_nanovg_Nanovg_nvgNVGtextRow_1next__JI_J(JThreadRuntime *runtime, s64 pptr, s32 pindex) {
    

    void*/*ptr*/ _re_val = nvgNVGtextRow_next((struct NVGtextRow*/*ptr*/)pptr, (int)pindex);
    return *((s64*)&_re_val);
    
}

s64 func_org_mini_nanovg_Nanovg_nvgCreateNVGglyphPosition__I_J(JThreadRuntime *runtime, s32 pcount) {
    

    struct NVGglyphPosition*/*ptr*/ _re_val = nvgCreateNVGglyphPosition((int)pcount);
    return *((s64*)&_re_val);
    
}

void func_org_mini_nanovg_Nanovg_nvgDeleteNVGglyphPosition__J_V(JThreadRuntime *runtime, s64 pval) {
    

    nvgDeleteNVGglyphPosition((struct NVGglyphPosition*/*ptr*/)pval);
    
    
}

f32 func_org_mini_nanovg_Nanovg_nvgNVGglyphPosition_1x__JI_F(JThreadRuntime *runtime, s64 pptr, s32 pcount) {
    

    return (f32)nvgNVGglyphPosition_x((struct NVGglyphPosition*/*ptr*/)pptr, (int)pcount);
    
    
}

f32 func_org_mini_nanovg_Nanovg_nvgTextJni__JFF_3BII_F(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, JArray *pstring, s32 pstart, s32 pend) {
    
    __refer ptr_pstring = pstring?pstring->prop.as_s8_arr:NULL;

    return (f32)nvgTextJni((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (const char*)(ptr_pstring), (int)pstart, (int)pend);
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTextBoxJni__JFFF_3BII_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, f32 pbreakRowWidth, JArray *pstring, s32 pstart, s32 pend) {
    
    __refer ptr_pstring = pstring?pstring->prop.as_s8_arr:NULL;

    nvgTextBoxJni((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (float)pbreakRowWidth, (const char*)(ptr_pstring), (int)pstart, (int)pend);
    
    
}

f32 func_org_mini_nanovg_Nanovg_nvgTextBoundsJni__JFF_3BII_3F_F(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, JArray *pstring, s32 pstart, s32 pend, JArray *pbounds) {
    
    __refer ptr_pstring = pstring?pstring->prop.as_s8_arr:NULL;
    __refer ptr_pbounds = pbounds?pbounds->prop.as_s8_arr:NULL;

    return (f32)nvgTextBoundsJni((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (const char*)(ptr_pstring), (int)pstart, (int)pend, (float*)(ptr_pbounds));
    
    
}

void func_org_mini_nanovg_Nanovg_nvgTextBoxBoundsJni__JFFF_3BII_3F_V(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, f32 pbreakRowWidth, JArray *pstring, s32 pstart, s32 pend, JArray *pbounds) {
    
    __refer ptr_pstring = pstring?pstring->prop.as_s8_arr:NULL;
    __refer ptr_pbounds = pbounds?pbounds->prop.as_s8_arr:NULL;

    nvgTextBoxBoundsJni((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (float)pbreakRowWidth, (const char*)(ptr_pstring), (int)pstart, (int)pend, (float*)(ptr_pbounds));
    
    
}

s32 func_org_mini_nanovg_Nanovg_nvgTextBreakLinesJni__J_3BIIFJI_I(JThreadRuntime *runtime, s64 pctx, JArray *pstring, s32 pstart, s32 pend, f32 pbreakRowWidth, s64 prows, s32 pmaxRows) {
    
    __refer ptr_pstring = pstring?pstring->prop.as_s8_arr:NULL;

    int _re_val = nvgTextBreakLinesJni((NVGcontext*/*ptr*/)pctx, (const char*)(ptr_pstring), (int)pstart, (int)pend, (float)pbreakRowWidth, (NVGtextRow*/*ptr*/)prows, (int)pmaxRows);
    return *((s32*)&_re_val);
    
}

s32 func_org_mini_nanovg_Nanovg_nvgTextGlyphPositionsJni__JFF_3BIIJI_I(JThreadRuntime *runtime, s64 pctx, f32 px, f32 py, JArray *pstring, s32 pstart, s32 pend, s64 ppositions, s32 pmaxPositions) {
    
    __refer ptr_pstring = pstring?pstring->prop.as_s8_arr:NULL;

    int _re_val = nvgTextGlyphPositionsJni((NVGcontext*/*ptr*/)pctx, (float)px, (float)py, (const char*)(ptr_pstring), (int)pstart, (int)pend, (NVGglyphPosition*/*ptr*/)ppositions, (int)pmaxPositions);
    return *((s32*)&_re_val);
    
}




