/*this file generated by Nanovg_java_2_c.java ,dont modify it manual.*/
#include <stdio.h>
#include <string.h>


#define DR_FLAC_IMPLEMENTATION

#include "dr_flac.h"  // Enables FLAC decoding.

#define DR_MP3_IMPLEMENTATION

#include "dr_mp3.h"   // Enables MP3 decoding.

//#define MA_DEBUG_OUTPUT

//#define MA_NO_COREAUDIO

#define MINIAUDIO_IMPLEMENTATION

#include "miniaudio.h"


#include "jvm.h"
#include "media.h"

//==========================================================================================
//callback
//==========================================================================================

typedef struct _S24Int {
    u8 c0;
    u8 c1;
    u8 c2;
} S24Int;
//
//void scaleSample(void *pSamples,ma_format format, s32 channels, s32 len, float scale){
//    if(len){
//        switch(format){
//            case ma_format_s16:{
//                ma_int16* dataPtr=pSamples;
//                s32 i, imax;
//                for (i=0,imax=len*channels;i<imax;i++){
//                    dataPtr[i]*=scale;
//                }
//                break;
//            }
//            case ma_format_u8:{
//                ma_uint8* dataPtr=pSamples;
//                s32 i, imax;
//                for (i=0,imax=len*channels;i<imax;i++){
//                    dataPtr[i]*=scale;
//                }
//                break;
//            }
//            case ma_format_f32:{
//                f32* dataPtr=pSamples;
//                s32 i, imax;
//                for (i=0,imax=len*channels;i<imax;i++){
//                    dataPtr[i]*=scale;
//                }
//                break;
//            }
//            case ma_format_s24:{
//                S24Int* dataPtr=pSamples;
//                S24Int elem;
//                s32 i, imax;
//                for (i=0,imax=len*channels;i<imax;i++){
//                    elem =dataPtr[i];
//                    s32 d=elem.c0|(elem.c1<<8)|(elem.c2<<16);
//                    d*=scale;
//                    elem.c0=d;
//                    elem.c1=d>>8;
//                    elem.c2=d>>16;
//                    dataPtr[i]=elem;
//                }
//                break;
//            }
//            case ma_format_s32:{
//                ma_int32* dataPtr=pSamples;
//                s32 i, imax;
//                for (i=0,imax=len*channels;i<imax;i++){
//                    dataPtr[i]*=scale;
//                }
//                break;
//            }
//        }
//
//    }
//}


void on_recv_frames(ma_device *pDevice, ma_uint32 frameCount, const void *pSamples) {
    if (refers._callback_minial_on_recv_frames) {
        JThreadRuntime *runtime;
        runtime = getRuntimeCurThread();
        if (runtime) {
            void (*func_ptr)(JThreadRuntime *runtime, s64 p0, s32 p2, s64 p3) =refers._callback_minial_on_recv_frames->raw->func_ptr;
            func_ptr(runtime, (s64) (intptr_t) pDevice, frameCount, (s64) (intptr_t) pSamples);
            exception_check_print(runtime);
        }
    }
}


ma_uint32 on_send_frames(ma_device *pDevice, ma_uint32 frameCount, void *pSamples) {
    if (refers._callback_minial_on_send_frames) {
        JThreadRuntime *runtime;
        runtime = getRuntimeCurThread();
        if (runtime) {

            s32 (*func_ptr)(JThreadRuntime *runtime, s64 p0, s32 p2, s64 p3) =refers._callback_minial_on_send_frames->raw->func_ptr;
            ma_uint32 ret = func_ptr(runtime, (s64) (intptr_t) pDevice, frameCount, (s64) (intptr_t) pSamples);
            exception_check_print(runtime);
            return ret;
        }
    }
    return 0;
}


void on_stop(ma_device *pDevice) {
    if (refers._callback_minial_on_stop) {
        JThreadRuntime *runtime;
        runtime = getRuntimeCurThread();
        if (runtime) {
            void (*func_ptr)(JThreadRuntime *runtime, s64 p0) =refers._callback_minial_on_stop->raw->func_ptr;
            func_ptr(runtime, (s64) (intptr_t) pDevice);
            exception_check_print(runtime);
        }
    }
}

void data_callback(ma_device *pDevice, void *pOutput, const void *pInput, ma_uint32 frameCount) {
    if (pInput)on_recv_frames(pDevice, frameCount, pInput);
    if (pOutput)on_send_frames(pDevice, frameCount, pOutput);
}
//==========================================================================================
//jni
//==========================================================================================

s64 func_org_mini_media_MiniAL_ma_1context_1init___J(JThreadRuntime *runtime) {

    ma_context *handle_context = jvm_calloc(sizeof(ma_context));
    if (ma_context_init(NULL, 0, NULL, handle_context) != MA_SUCCESS) {
        return 0;
    } else {
        return (s64) (intptr_t) handle_context;
    }
}

void func_org_mini_media_MiniAL_ma_1context_1uninit__J_V(JThreadRuntime *runtime, s64 p0) {

    if (p0)ma_context_uninit((__refer) (intptr_t) p0);
    jvm_free((__refer) (intptr_t) p0);
}


s64 func_org_mini_media_MiniAL_ma_1decoder_1init_1file___3BIII_J(JThreadRuntime *runtime, JArray *p0, s32 p1, s32 p2, s32 p3) {
    s32 format = p1;
    s32 channels = p2;
    s32 sampleRate = p3;


    ma_decoder_config mdc = ma_decoder_config_init(format, channels, sampleRate);

    ma_decoder *handle_decoder = jvm_calloc(sizeof(ma_decoder));
    if (ma_decoder_init_file(p0->prop.as_c8_arr, &mdc, handle_decoder) != MA_SUCCESS) {
        return 0;
    } else {
        return (s64) (intptr_t) handle_decoder;
    }
}


s64 func_org_mini_media_MiniAL_ma_1decoder_1init_1memory___3BIII_J(JThreadRuntime *runtime, JArray *p0, s32 p1, s32 p2, s32 p3) {
    s32 format = p1;
    s32 channels = p2;
    s32 sampleRate = p3;


    ma_decoder_config mdc = ma_decoder_config_init(format, channels, sampleRate);

    ma_decoder *handle_decoder = jvm_calloc(sizeof(ma_decoder));
    if (ma_decoder_init_memory(p0->prop.as_c8_arr, p0->prop.arr_length, &mdc, handle_decoder) != MA_SUCCESS) {
        return 0;
    } else {
        return (s64) (intptr_t) handle_decoder;
    }
}

void func_org_mini_media_MiniAL_ma_1decoder_1get_1para__J_3I_V(JThreadRuntime *runtime, s64 p0, JArray *p2) {
    ma_decoder *handle_decoder = (__refer) (intptr_t) p0;
    if (handle_decoder && p2->prop.arr_length >= 3) {
        p2->prop.as_s32_arr[0] = handle_decoder->outputFormat;
        p2->prop.as_s32_arr[1] = handle_decoder->outputChannels;
        p2->prop.as_s32_arr[2] = handle_decoder->outputSampleRate;
    }
}

s32 func_org_mini_media_MiniAL_ma_1decoder_1read__JIJ_I(JThreadRuntime *runtime, s64 p0, s32 p2, s64 p3) {
    ma_decoder *handle_decoder = (__refer) (intptr_t) p0;
    s32 frameCount = p2;
    __refer pSamples = (__refer) (intptr_t) p3;


    if (handle_decoder) {
        s32 v = (ma_uint32) ma_decoder_read_pcm_frames(handle_decoder, pSamples, frameCount);
        return v;
    } else {
        return -1;
    }
}

void func_org_mini_media_MiniAL_ma_1decoder_1uninit__J_V(JThreadRuntime *runtime, s64 p0) {
    ma_decoder *handle_decoder = (__refer) (intptr_t) p0;

    if (handle_decoder)ma_decoder_uninit(handle_decoder);
    jvm_free(handle_decoder);
}

void setupCallback(JThreadRuntime *runtime) {
    c8 *name_s;
    c8 *type_s;
    c8 *clsname_s;
    if (!refers._callback_minial_on_recv_frames) {
        clsname_s = "org/mini/media/AudioDevice";
        name_s = "onReceiveFrames";
        type_s = "(JIJ)V";
        refers._callback_minial_on_recv_frames = find_methodInfo_by_name(clsname_s, name_s, type_s);
    }
    if (!refers._callback_minial_on_send_frames) {
        clsname_s = "org/mini/media/AudioDevice";
        name_s = "onSendFrames";
        type_s = "(JIJ)I";
        refers._callback_minial_on_send_frames = find_methodInfo_by_name(clsname_s, name_s, type_s);
    }
    if (!refers._callback_minial_on_stop) {
        clsname_s = "org/mini/media/AudioDevice";
        name_s = "onStop";
        type_s = "(J)V";
        refers._callback_minial_on_stop = find_methodInfo_by_name(clsname_s, name_s, type_s);
    }

}

s64 func_org_mini_media_MiniAL_ma_1device_1init__JIJIII_J(JThreadRuntime *runtime, s64 p0, s32 p2, s64 p3, s32 p5, s32 p6, s32 p7) {

    ma_context *handle_context = (__refer) (intptr_t) p0;
    s32 deviceType = p2;
    __refer handle_userdata = (__refer) (intptr_t) p3;
    s32 format = p5;
    s32 channels = p6;
    s32 sampleRate = p7;

    setupCallback(runtime);

    ma_device_config dev_cfg = ma_device_config_init(deviceType);
    dev_cfg.playback.format = format;
    dev_cfg.playback.channels = channels;
    dev_cfg.capture.format = format;
    dev_cfg.capture.channels = channels;
    dev_cfg.sampleRate = sampleRate;
    dev_cfg.dataCallback = data_callback;
    dev_cfg.stopCallback = on_stop;
    dev_cfg.pUserData = handle_userdata;

    ma_device *handle_device = jvm_calloc(sizeof(ma_device));
    if (ma_device_init(handle_context, &dev_cfg, handle_device) != MA_SUCCESS) {
        return 0;
    } else {
        return (s64) (intptr_t) handle_device;
    }
}

void func_org_mini_media_MiniAL_ma_1device_1uninit__J_V(JThreadRuntime *runtime, s64 p0) {
    __refer handle_device = (__refer) (intptr_t) p0;

    ma_device_uninit(handle_device);
    jvm_free(handle_device);
}

void func_org_mini_media_MiniAL_ma_1device_1start__J_V(JThreadRuntime *runtime, s64 p0) {
    __refer handle_device = (__refer) (intptr_t) p0;
    ma_device_start(handle_device);
}

void func_org_mini_media_MiniAL_ma_1device_1stop__J_V(JThreadRuntime *runtime, s64 p0) {
    __refer handle_device = (__refer) (intptr_t) p0;
    ma_device_stop(handle_device);
}

s32 func_org_mini_media_MiniAL_ma_1device_1is_1started__J_I(JThreadRuntime *runtime, s64 p0) {
    __refer handle_device = (__refer) (intptr_t) p0;
    ma_bool32 r = ma_device_is_started(handle_device);
    return (s32) (intptr_t) r;
}

//static java_native_method method_minial_table[] = {
//
//        {"org/mini/media/MiniAL", "ma_context_init",        "()J",      org_mini_media_MiniAL_ma_context_init},
//        {"org/mini/media/MiniAL", "ma_context_uninit",      "(J)V",     org_mini_media_MiniAL_ma_context_uninit},
//        {"org/mini/media/MiniAL", "ma_decoder_init_file",   "([BIII)J", org_mini_media_MiniAL_ma_decoder_init_file},
//        {"org/mini/media/MiniAL", "ma_decoder_init_memory", "([BIII)J", org_mini_media_MiniAL_ma_decoder_init_memory},
//        {"org/mini/media/MiniAL", "ma_decoder_get_para",    "(J[I)V",    org_mini_media_MiniAL_ma_decoder_get_para},
//        {"org/mini/media/MiniAL", "ma_decoder_read",        "(JIJ)I",   org_mini_media_MiniAL_ma_decoder_read},
//        {"org/mini/media/MiniAL", "ma_decoder_uninit",      "(J)V",     org_mini_media_MiniAL_ma_decoder_uninit},
//        {"org/mini/media/MiniAL", "ma_device_init",         "(JIJIII)J",  org_mini_media_MiniAL_ma_device_init},
//        {"org/mini/media/MiniAL", "ma_device_uninit",       "(J)V",     org_mini_media_MiniAL_ma_device_uninit},
//        {"org/mini/media/MiniAL", "ma_device_start",        "(J)V",     org_mini_media_MiniAL_ma_device_start},
//        {"org/mini/media/MiniAL", "ma_device_stop",         "(J)V",     org_mini_media_MiniAL_ma_device_stop},
//        {"org/mini/media/MiniAL", "ma_device_is_started",   "(J)I",     org_mini_media_MiniAL_ma_device_is_started},
//};
//
//s32 count_MiniALFuncTable() {
//    return sizeof(method_minial_table) / sizeof(java_native_method);
//}
//
//__refer ptr_MiniALFuncTable() {
//    return &method_minial_table[0];
//}
